## 1.Download the datasets

### 1.1 Download the multi-omics data

* parse the multiomics data from the synapse website of the dataset ROSMAP https://www.synapse.org/#!Synapse:syn23446022
* Genome Variants https://www.synapse.org/#!Synapse:syn26263118
* Methylation https://www.synapse.org/#!Synapse:syn3168763
* RNA sequence https://www.synapse.org/#!Synapse:syn3505720
* Proteomics https://www.synapse.org/#!Synapse:syn21266454

### 1.2 Download the clinical data

* parse the clinical data https://www.synapse.org/#!Synapse:syn3191087

## 2.Read the files

In [1]:
import pandas as pd
from pyensembl import EnsemblRelease

### 2.1 Read DNA methylation data

In [2]:
methylation_value = pd.read_csv("./ROSMAP-raw/Methylation/DNA-methylation-array/AMP-AD_ROSMAP_Rush-Broad_IlluminaHumanMethylation450_740_imputed.tsv",sep='\t')

In [3]:
methylation_value

,TargetID,TBI-AUTO73325-PT-3149,PT-BZHL,PT-BZCH,PT-BY9H,TBI-AUTO73307-PT-314I,TBI-AUTO73043-PT-35BD,PT-BZI5,PT-BZ1A,PT-318X,...,TBI-AUTO72955-PT-35OC,TBI-AUTO73291-PT-35OD,PT-BZD7,PT-BZG8,PT-C1N8,PT-BYJP,PT-BZHV,PT-BZI2,TBI-AUTO73257-PT-35OE,PT-BZD3
0,cg00000165,0.231359,0.157857,0.127105,0.149988,0.130532,0.174451,0.170026,0.165900,0.157745,...,0.124635,0.168002,0.152200,0.230482,0.177287,0.195611,0.151338,0.151508,0.167960,0.136220
1,cg00000363,0.140664,0.114399,0.140580,0.145805,0.122833,0.117144,0.155559,0.131309,0.157749,...,0.129301,0.126910,0.135973,0.162883,0.122399,0.112684,0.125054,0.118550,0.114618,0.133814
2,cg00000957,0.776220,0.818279,0.630316,0.849261,0.861136,0.751543,0.778917,0.859892,0.787279,...,0.735520,0.740686,0.748494,0.797072,0.793081,0.692638,0.785597,0.712386,0.839168,0.888304
3,cg00001349,0.865488,0.919570,0.882256,0.902912,0.907610,0.897496,0.939212,0.919514,0.805626,...,0.885292,0.900684,0.906257,0.756173,0.948341,0.904996,0.927201,0.856637,0.917827,0.943320
4,cg00001364,0.772899,0.711099,0.694639,0.651986,0.748538,0.706625,0.743491,0.712513,0.722169,...,0.720420,0.724226,0.694462,0.776165,0.758569,0.733207,0.750224,0.737402,0.685959,0.770543
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420127,ch.22.772318F,0.233366,0.198370,0.176775,0.141996,0.167610,0.252353,0.153457,0.124837,0.224565,...,0.253596,0.184639,0.175109,0.183692,0.000000,0.193311,0.149942,0.135414,0.123727,0.121499
420128,ch.22.43177094F,0.173744,0.199095,0.189069,0.226845,0.193875,0.194734,0.194701,0.207784,0.183201,...,0.225843,0.172531,0.234507,0.169050,0.177599,0.205192,0.176225,0.191057,0.204723,0.179136
420129,ch.22.909671F,0.409177,0.463476,0.307656,0.302488,0.426867,0.425683,0.335775,0.361516,0.385871,...,0.431509,0.390838,0.402118,0.382906,0.410532,0.472419,0.340013,0.436682,0.413712,0.447053
420130,ch.22.46830341F,0.225070,0.279521,0.224084,0.286071,0.272743,0.322463,0.271097,0.268207,0.250027,...,0.267995,0.279551,0.333601,0.305278,0.280626,0.344297,0.251353,0.233328,0.280114,0.306628
420131,ch.22.1008279F,0.067878,0.072976,0.090009,0.051107,0.072089,0.110484,0.059588,0.036466,0.044706,...,0.053982,0.068004,0.079603,0.048614,0.080189,0.095757,0.051977,0.057825,0.071150,0.055774

### 2.2 Read Platform annotations for 450k methylation

In [4]:
# Reading and processing basic data
try:
    annotation = pd.read_table('./ROSMAP-raw/Methylation/DNA-methylation-array/GPL16304-47833.txt', delimiter='\t')
    annotation['Distance_closest_TSS'] = annotation['Distance_closest_TSS'].astype(int)
    annotation = annotation[~annotation['Closest_TSS'].apply(lambda x: len(str(x).split(';')) > 1)]
except ValueError as e:
    print(f"Unable to convert 'Closest_TSS' column to integer: {e}")
    problematic_rows = annotation['Distance_closest_TSS'].apply(lambda x: not str(x).isnumeric())
    print("Problematic rows:")
    print(annotation.loc[problematic_rows])

annotation

C:\Users\Lilab\AppData\Local\Temp\ipykernel_34020\1730697995.py:3: DtypeWarning: Columns (16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  annotation = pd.read_table('./ROSMAP-raw/Methylation/DNA-methylation-array/GPL16304-47833.txt', delimiter='\t')

,ID,MAPINFO-1,MAPINFO+1,Probe_start,Probe_end,Target CpG SNP,n_target CpG SNP,SNPprobe,n_SNPprobe,HIL_CpG_class,...,AlleleA_Hits,AlleleB_Hits,XY_Hits,Autosomal_Hits,Closest_TSS,Closest_TSS_1,Distance_closest_TSS,Closest_TSS_gene_name,Closest_TSS_Transcript,SPOT_ID
0,cg00000029,53468111,53468113,53468112,53468162,NaN,NaN,NaN,NaN,HC,...,1,0,XY_NO,A_NO,53468350,53468351,-238,RBL2,NM_005611,cg00000029
1,cg00000108,37459205,37459207,37459206,37459256,NaN,NaN,rs9857774,1.0,LC,...,1,0,XY_NO,A_NO,37458757,37458758,449,C3orf35,CCDS46792,cg00000108
2,cg00000109,171916036,171916038,171916037,171916087,NaN,NaN,rs9864492,1.0,LC,...,1,0,XY_NO,A_NO,171851260,171851261,64777,FNDC3B,AY358367,cg00000109
3,cg00000165,91194673,91194675,91194624,91194674,NaN,NaN,rs76771611,1.0,ICshore,...,1,0,XY_NO,A_NO,91182793,91182794,-11880,BARHL2,NM_020063,cg00000165
4,cg00000236,42263293,42263295,42263244,42263294,NaN,NaN,NaN,NaN,IC,...,1,0,XY_NO,A_NO,42251727,42251728,11567,VDAC3,CCDS47850,cg00000236
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485507,ch.X.97129969R,97243312,97243314,97243313,97243363,NaN,NaN,NaN,NaN,LC,...,1,0,XY_NO,A_NO,97607750,97607751,-364437,Mir_340,.,ch.X.97129969R
485508,ch.X.97133160R,97246503,97246505,97246504,97246554,NaN,NaN,NaN,NaN,LC,...,2,0,XY_NO,A_YES,97607750,97607751,-361246,Mir_340,.,ch.X.97133160R
485509,ch.X.97651759F,97765102,97765104,97765103,97765153,NaN,NaN,NaN,NaN,LC,...,1,0,XY_NO,A_NO,97607750,97607751,157353,Mir_340,.,ch.X.97651759F
485510,ch.X.97737721F,97851064,97851066,97851065,97851115,NaN,NaN,NaN,NaN,LC,...,21,0,XY_NO,A_YES,97607750,97607751,243315,Mir_340,.,ch.X.97737721F
485511,ch.X.98007042R,98120385,98120387,98120386,98120436,NaN,NaN,NaN,NaN,LC,...,1,0,XY_NO,A_NO,97607750,97607751,512636,Mir_340,.,ch.X.98007042R

In [5]:
map_annotation= annotation[['ID', 'Closest_TSS','Closest_TSS_gene_name', 'Distance_closest_TSS']]
map_annotation

                    ID Closest_TSS Closest_TSS_gene_name  Distance_closest_TSS
0           cg00000029    53468350                  RBL2                  -238
1           cg00000108    37458757               C3orf35                   449
2           cg00000109   171851260                FNDC3B                 64777
3           cg00000165    91182793                BARHL2                -11880
4           cg00000236    42251727                 VDAC3                 11567
...                ...         ...                   ...                   ...
485507  ch.X.97129969R    97607750               Mir_340               -364437
485508  ch.X.97133160R    97607750               Mir_340               -361246
485509  ch.X.97651759F    97607750               Mir_340                157353
485510  ch.X.97737721F    97607750               Mir_340                243315
485511  ch.X.98007042R    97607750               Mir_340                512636

[485493 rows x 4 columns]

### 2.3 Read gene expression data, mapping information and substitue the the gene name

In [6]:
gene_expression = pd.read_csv('./ROSMAP-raw/RNASeq/ROSMAP_RNAseq_FPKM_gene.tsv', sep='\t')
gene_expression

,tracking_id,gene_id,525_120515_0,383_120503_0,93_120417_0,610_120523_0,560_120517_0,492_120515_0,576_120521_0,150_120419_0,...,831_130725_8,901_131010_8,894_130923_8,938_131101_8,942_131101_8,939_131101_8,895_130923_8,829_130725_8,944_131107_8,775_130528_8
0,ENSG00000167578.11,ENSG00000167578.11,60.84,65.45,69.18,51.60,48.61,55.65,51.18,60.63,...,44.85,45.02,33.71,38.30,28.27,51.02,31.87,37.14,41.77,44.01
1,ENSG00000242268.1,ENSG00000242268.1,0.08,0.05,0.08,0.08,0.10,0.08,0.06,0.11,...,0.00,0.10,0.20,0.00,0.00,0.00,0.00,0.00,0.09,0.10
2,ENSG00000078237.4,ENSG00000078237.4,4.39,4.49,2.51,2.90,2.67,5.50,3.36,3.43,...,8.15,4.05,6.06,6.03,4.34,5.16,2.70,5.00,3.82,3.69
3,ENSG00000263642.1,ENSG00000263642.1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,ENSG00000225275.4,ENSG00000225275.4,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55884,ENSG00000265520.1,ENSG00000265520.1,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
55885,ENSG00000231119.2,ENSG00000231119.2,0.20,0.20,0.24,0.21,0.09,0.14,0.42,0.26,...,0.22,0.11,0.18,0.24,0.14,0.28,0.24,0.15,0.23,0.15
55886,ENSG00000105063.14,ENSG00000105063.14,40.59,39.26,34.70,36.74,39.85,35.28,24.78,31.14,...,28.82,24.08,24.10,24.81,27.30,22.24,20.08,23.68,17.91,26.37
55887,ENSG00000123685.4,ENSG00000123685.4,4.46,4.51,5.27,5.11,3.77,4.31,4.63,4.40,...,3.03,5.06,2.05,4.01,2.89,2.69,3.42,4.25,5.46,3.65
55888,ENSG00000181518.2,ENSG00000181518.2,0.00,0.00,0.05,0.05,0.00,0.00,0.02,0.00,...,0.20,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [7]:
ensembl_gene_ids = gene_expression['gene_id'].apply(lambda x: x.split('.')[0]).tolist()
gene_expression['gene_id'] = ensembl_gene_ids
gene_expression

,tracking_id,gene_id,525_120515_0,383_120503_0,93_120417_0,610_120523_0,560_120517_0,492_120515_0,576_120521_0,150_120419_0,...,831_130725_8,901_131010_8,894_130923_8,938_131101_8,942_131101_8,939_131101_8,895_130923_8,829_130725_8,944_131107_8,775_130528_8
0,ENSG00000167578.11,ENSG00000167578,60.84,65.45,69.18,51.60,48.61,55.65,51.18,60.63,...,44.85,45.02,33.71,38.30,28.27,51.02,31.87,37.14,41.77,44.01
1,ENSG00000242268.1,ENSG00000242268,0.08,0.05,0.08,0.08,0.10,0.08,0.06,0.11,...,0.00,0.10,0.20,0.00,0.00,0.00,0.00,0.00,0.09,0.10
2,ENSG00000078237.4,ENSG00000078237,4.39,4.49,2.51,2.90,2.67,5.50,3.36,3.43,...,8.15,4.05,6.06,6.03,4.34,5.16,2.70,5.00,3.82,3.69
3,ENSG00000263642.1,ENSG00000263642,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,ENSG00000225275.4,ENSG00000225275,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55884,ENSG00000265520.1,ENSG00000265520,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
55885,ENSG00000231119.2,ENSG00000231119,0.20,0.20,0.24,0.21,0.09,0.14,0.42,0.26,...,0.22,0.11,0.18,0.24,0.14,0.28,0.24,0.15,0.23,0.15
55886,ENSG00000105063.14,ENSG00000105063,40.59,39.26,34.70,36.74,39.85,35.28,24.78,31.14,...,28.82,24.08,24.10,24.81,27.30,22.24,20.08,23.68,17.91,26.37
55887,ENSG00000123685.4,ENSG00000123685,4.46,4.51,5.27,5.11,3.77,4.31,4.63,4.40,...,3.03,5.06,2.05,4.01,2.89,2.69,3.42,4.25,5.46,3.65
55888,ENSG00000181518.2,ENSG00000181518,0.00,0.00,0.05,0.05,0.00,0.00,0.02,0.00,...,0.20,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [8]:
ensembl_data_unique_gene = pd.read_csv("./ROSMAP-raw/Meta-Data/mart_export_unique_gene.txt")
ensembl_data_unique_gene

      Gene name
0         MT-TF
1       MT-RNR1
2         MT-TV
3       MT-RNR2
4        MT-TL1
...         ...
48105    ZNF593
48106    CNKSR1
48107    ZPLD2P
48108   DDX11L2
48109    WASH7P

[48110 rows x 1 columns]

In [9]:
ensembl_data = pd.read_csv("./ROSMAP-raw/Meta-Data/mart_export_genename.txt")
ensembl_data= ensembl_data.rename(columns={'Gene stable ID': 'gene_id'})
ensembl_data

               gene_id Gene name
0      ENSG00000210049     MT-TF
1      ENSG00000211459   MT-RNR1
2      ENSG00000210077     MT-TV
3      ENSG00000210082   MT-RNR2
4      ENSG00000209082    MT-TL1
...                ...       ...
70706  ENSG00000288629       NaN
70707  ENSG00000288678       NaN
70708  ENSG00000290825   DDX11L2
70709  ENSG00000227232    WASH7P
70710  ENSG00000290826       NaN

[70711 rows x 2 columns]

In [10]:
ensembl_data = ensembl_data.dropna()
ensembl_data = ensembl_data.drop_duplicates()
ensembl_data

               gene_id Gene name
0      ENSG00000210049     MT-TF
1      ENSG00000211459   MT-RNR1
2      ENSG00000210077     MT-TV
3      ENSG00000210082   MT-RNR2
4      ENSG00000209082    MT-TL1
...                ...       ...
70701  ENSG00000142684    ZNF593
70702  ENSG00000142675    CNKSR1
70703  ENSG00000293494    ZPLD2P
70708  ENSG00000290825   DDX11L2
70709  ENSG00000227232    WASH7P

[48110 rows x 2 columns]

In [11]:
# Now, merge the two dataframes on the 'gene_name' column
merged_data = pd.merge(gene_expression, ensembl_data, on='gene_id', how='inner')
merged_data

,tracking_id,gene_id,525_120515_0,383_120503_0,93_120417_0,610_120523_0,560_120517_0,492_120515_0,576_120521_0,150_120419_0,...,901_131010_8,894_130923_8,938_131101_8,942_131101_8,939_131101_8,895_130923_8,829_130725_8,944_131107_8,775_130528_8,Gene name
0,ENSG00000167578.11,ENSG00000167578,60.84,65.45,69.18,51.60,48.61,55.65,51.18,60.63,...,45.02,33.71,38.30,28.27,51.02,31.87,37.14,41.77,44.01,RAB4B
1,ENSG00000242268.1,ENSG00000242268,0.08,0.05,0.08,0.08,0.10,0.08,0.06,0.11,...,0.10,0.20,0.00,0.00,0.00,0.00,0.00,0.09,0.10,LINC02082
2,ENSG00000078237.4,ENSG00000078237,4.39,4.49,2.51,2.90,2.67,5.50,3.36,3.43,...,4.05,6.06,6.03,4.34,5.16,2.70,5.00,3.82,3.69,TIGAR
3,ENSG00000263642.1,ENSG00000263642,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,MIR4802
4,ENSG00000225275.4,ENSG00000225275,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NUP210P2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38777,ENSG00000148943.7,ENSG00000148943,10.02,8.76,6.28,8.32,8.68,8.93,9.85,10.67,...,11.47,14.18,13.93,15.96,14.90,11.57,11.81,15.92,12.16,LIN7C
38778,ENSG00000265520.1,ENSG00000265520,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,MIR548V
38779,ENSG00000105063.14,ENSG00000105063,40.59,39.26,34.70,36.74,39.85,35.28,24.78,31.14,...,24.08,24.10,24.81,27.30,22.24,20.08,23.68,17.91,26.37,PPP6R1
38780,ENSG00000123685.4,ENSG00000123685,4.46,4.51,5.27,5.11,3.77,4.31,4.63,4.40,...,5.06,2.05,4.01,2.89,2.69,3.42,4.25,5.46,3.65,BATF3
38781,ENSG00000181518.2,ENSG00000181518,0.00,0.00,0.05,0.05,0.00,0.00,0.02,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,OR8D4

In [12]:
merged_data = merged_data.rename(columns={'Gene name': 'gene_name'})
merged_data.replace('Nan', pd.NA, inplace=True)  # Replace 'Nan' string with actual NaN
merged_data.dropna(subset=['gene_name'], inplace=True)  # Drop rows with NaN values
merged_data

,tracking_id,gene_id,525_120515_0,383_120503_0,93_120417_0,610_120523_0,560_120517_0,492_120515_0,576_120521_0,150_120419_0,...,901_131010_8,894_130923_8,938_131101_8,942_131101_8,939_131101_8,895_130923_8,829_130725_8,944_131107_8,775_130528_8,gene_name
0,ENSG00000167578.11,ENSG00000167578,60.84,65.45,69.18,51.60,48.61,55.65,51.18,60.63,...,45.02,33.71,38.30,28.27,51.02,31.87,37.14,41.77,44.01,RAB4B
1,ENSG00000242268.1,ENSG00000242268,0.08,0.05,0.08,0.08,0.10,0.08,0.06,0.11,...,0.10,0.20,0.00,0.00,0.00,0.00,0.00,0.09,0.10,LINC02082
2,ENSG00000078237.4,ENSG00000078237,4.39,4.49,2.51,2.90,2.67,5.50,3.36,3.43,...,4.05,6.06,6.03,4.34,5.16,2.70,5.00,3.82,3.69,TIGAR
3,ENSG00000263642.1,ENSG00000263642,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,MIR4802
4,ENSG00000225275.4,ENSG00000225275,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NUP210P2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38777,ENSG00000148943.7,ENSG00000148943,10.02,8.76,6.28,8.32,8.68,8.93,9.85,10.67,...,11.47,14.18,13.93,15.96,14.90,11.57,11.81,15.92,12.16,LIN7C
38778,ENSG00000265520.1,ENSG00000265520,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,MIR548V
38779,ENSG00000105063.14,ENSG00000105063,40.59,39.26,34.70,36.74,39.85,35.28,24.78,31.14,...,24.08,24.10,24.81,27.30,22.24,20.08,23.68,17.91,26.37,PPP6R1
38780,ENSG00000123685.4,ENSG00000123685,4.46,4.51,5.27,5.11,3.77,4.31,4.63,4.40,...,5.06,2.05,4.01,2.89,2.69,3.42,4.25,5.46,3.65,BATF3
38781,ENSG00000181518.2,ENSG00000181518,0.00,0.00,0.05,0.05,0.00,0.00,0.02,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,OR8D4

In [13]:
import numpy as np
cols = ['gene_name'] + [col for col in merged_data if col != 'gene_name']
gene_expression_new = merged_data[cols]
numeric_cols = gene_expression_new.select_dtypes(include=[np.number]).columns.tolist()

# Now, we group by 'gene_name' and calculate the mean of all numeric columns
gene_expression_new = gene_expression_new.groupby('gene_name')[numeric_cols].mean()

# Reset the index to turn the grouped keys (gene_name) back into a column
gene_expression_new.reset_index(inplace=True)
gene_expression_new

,gene_name,525_120515_0,383_120503_0,93_120417_0,610_120523_0,560_120517_0,492_120515_0,576_120521_0,150_120419_0,416_120503_0,...,831_130725_8,901_131010_8,894_130923_8,938_131101_8,942_131101_8,939_131101_8,895_130923_8,829_130725_8,944_131107_8,775_130528_8
0,7SK,233.11,148.79,177.12,197.38,238.15,156.24,340.67,111.16,212.84,...,63.46,70.21,89.59,85.90,140.91,132.21,125.26,67.56,111.18,89.51
1,A1BG,2.93,2.44,3.78,2.82,3.26,3.19,3.40,3.62,2.82,...,1.23,1.86,1.66,1.59,1.32,1.59,1.03,1.95,3.23,1.98
2,A1CF,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3,A2M,15.37,16.15,31.83,32.41,29.42,33.33,46.22,30.92,42.70,...,26.35,33.72,46.68,34.92,32.48,26.25,62.94,25.71,21.72,34.44
4,A2M-AS1,0.59,0.79,0.71,0.63,0.39,0.77,0.34,0.57,0.45,...,1.18,0.95,0.57,0.76,0.45,1.40,0.75,1.09,1.52,0.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37893,ZYG11B,10.24,7.94,6.20,6.08,5.98,17.90,5.65,10.92,7.60,...,17.64,16.46,14.33,13.96,11.23,14.36,8.10,12.67,14.02,11.08
37894,ZYX,55.86,62.33,77.69,54.95,55.05,49.34,62.83,86.67,69.39,...,42.19,50.30,47.13,36.20,32.47,41.14,33.11,55.77,35.80,44.74
37895,ZZEF1,5.57,6.09,5.19,5.36,5.53,8.74,9.64,9.37,6.14,...,5.91,8.76,6.18,5.91,6.18,5.03,4.97,5.45,6.13,6.53
37896,ZZZ3,4.73,5.13,3.41,4.87,5.21,6.66,5.09,5.12,4.76,...,8.89,6.25,8.17,8.35,8.74,7.51,6.41,6.73,9.76,8.06
37897,hsa-mir-423,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [14]:
# import pandas as pd
# from pyensembl import EnsemblRelease

# # Function to fetch the requested information for a gene ID
# def fetch_gene_info(gene_id_with_version, ensembl_data, attributes):
#     # Split the gene_id to exclude the version number
#     gene_id = gene_id_with_version.split('.')[0]
#     info = {}
#     try:
#         gene = ensembl_data.gene_by_id(gene_id)
#         for attribute in attributes:
#             value = None
#             if hasattr(gene, attribute):
#                 value = getattr(gene, attribute)
#             elif attribute == 'transcript_names':
#                 value = ','.join([t.name for t in gene.transcripts])
#             elif attribute == 'transcript_ids':
#                 value = ','.join([t.transcript_id for t in gene.transcripts])
#             elif attribute == 'exon_ids':
#                 exons = [exon.exon_id for transcript in gene.transcripts for exon in transcript.exons]
#                 value = ','.join(exons)
#             info[attribute] = value
#     except ValueError:
#         # If gene ID is not found, fill all attributes with "ValueError"
#         for attribute in attributes:
#             info[attribute] = "ValueError"
#     return info

# # Main function to update the CSV file with the requested gene information
# def update_csv_with_gene_attributes(csv_path, attributes):
#     # Load the CSV file
#     data = pd.read_csv(csv_path, sep='\t')

#     # Initialize the Ensembl data
#     ensembl_data = EnsemblRelease()
#     ensembl_data.download()
#     ensembl_data.index()

#     # Fetch and add the requested gene-related information
#     for attribute in attributes:
#         # Apply the fetch_gene_info function for each gene_id and extract the attribute
#         data[attribute] = data['gene_id'].apply(lambda gene_id: fetch_gene_info(gene_id, ensembl_data, attributes)[attribute])

#     # Save the updated CSV file
#     updated_csv_path = csv_path.replace('.tsv', '_with_attributes.tsv')
#     data.to_csv(updated_csv_path, sep='\t', index=False)
#     return updated_csv_path

In [15]:
# # input the file path and additional attributes you want:
# csv_file_path = './ROSMAP-raw/RNASeq/ROSMAP_RNAseq_FPKM_gene.tsv' 
# attributes_to_add = ['gene_name'] 

# # Call the function with the CSV path and the list of attributes
# updated_file_path = update_csv_with_gene_attributes(csv_file_path, attributes_to_add)
# print(f"Updated CSV file is saved at {updated_file_path}")

In [16]:
# #Read the new gene_expression with gene_name
# gene_expression = pd.read_csv('./ROSMAP-raw/RNASeq/ROSMAP_RNAseq_FPKM_gene_with_attributes.tsv', sep='\t')
# gene_expression

In [17]:
# #Check if any gene names have not been found
# count = gene_expression[gene_expression['gene_name'] == 'Gene name not found'].shape[0]
# count

In [18]:
# # set gene to the first column
# cols = ['gene_name'] + [col for col in gene_expression if col != 'gene_name']
# gene_expression_new = gene_expression[cols]
# gene_expression_new.drop(columns=['tracking_id', 'gene_id'], inplace=True)

In [19]:
# gene_expression_new = gene_expression_new.dropna(subset=['gene_name'])
# gene_expression_new = gene_expression_new.groupby('gene_name', as_index=False).mean()
# gene_expression_new = gene_expression_new.reset_index(drop=True)
# gene_expression_new

### 2.4 Read clinical data

In [20]:
survival = pd.read_csv('./ROSMAP-raw/ROSMAP_clinical/ROSMAP_clinical.csv', sep=',')
survival

,projid,Study,msex,educ,race,spanish,apoe_genotype,age_at_visit_max,age_first_ad_dx,age_death,cts_mmse30_first_ad_dx,cts_mmse30_lv,pmi,braaksc,ceradsc,cogdx,dcfdx_lv,individualID
0,10101589,ROS,1.0,20.0,1.0,2.0,34.0,90+,90+,90+,18.0,5.0,9.916667,4.0,2.0,4.0,4.0,R6939144
1,86767530,MAP,0.0,10.0,1.0,2.0,33.0,90+,90+,90+,18.0,10.0,6.500000,4.0,2.0,4.0,4.0,R3893503
2,9650662,MAP,0.0,15.0,1.0,2.0,23.0,90+,90+,90+,0.0,0.0,3.850000,3.0,2.0,4.0,4.0,R8937093
3,50402855,MAP,0.0,21.0,1.0,2.0,33.0,90+,NaN,NaN,NaN,27.0,NaN,NaN,NaN,NaN,1.0,R7139444
4,20544321,ROS,0.0,16.0,1.0,2.0,23.0,90+,90+,NaN,13.0,14.0,NaN,NaN,NaN,NaN,4.0,R4971237
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3579,22207815,ROS,0.0,18.0,2.0,2.0,23.0,57.653661875427787,NaN,NaN,NaN,29.0,NaN,NaN,NaN,NaN,1.0,R5306025
3580,22207941,ROS,0.0,16.0,2.0,2.0,34.0,56.651608487337441,NaN,NaN,NaN,27.0,NaN,NaN,NaN,NaN,1.0,R6142763
3581,49333806,MAP,0.0,12.0,2.0,2.0,NaN,56.599589322381931,NaN,NaN,NaN,30.0,NaN,NaN,NaN,NaN,1.0,R4468842
3582,59720188,MAP,0.0,13.0,1.0,1.0,NaN,54.622861054072551,NaN,NaN,NaN,29.0,NaN,NaN,NaN,NaN,1.0,R9446033
3583,90214403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,R5615105

### 2.5 Read proteomics data

In [21]:
protein = pd.read_csv("./ROSMAP-raw/Proteomics/C2.median_polish_corrected_log2(abundanceRatioCenteredOnMedianOfBatchMediansPerProtein)-8817x400.csv",sep=',')
protein

,Unnamed: 0,b01.127C,b01.127N,b01.128C,b01.128N,b01.129C,b01.129N,b01.130C,b01.130N,b02.127C,...,b49.130C,b49.130N,b50.127C,b50.127N,b50.128C,b50.128N,b50.129C,b50.129N,b50.130C,b50.130N
0,VAMP1|P23763,-0.278255,0.410722,-0.112329,-0.162641,-0.071647,0.117440,-0.042157,0.187085,-0.835022,...,-0.073641,0.081353,0.084443,-0.220764,0.231834,-0.076819,-0.130791,-0.173961,-0.043709,-0.054343
1,KCTD13|Q8WZ19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.225794,0.019362,0.393129,0.238450,-0.039415,0.313539,0.335718,0.197204
2,TXNDC12|O95881,-0.366508,-0.498610,-0.276421,-0.354865,-0.238212,-0.321546,-0.213956,-0.532379,-0.742539,...,-0.521676,-0.289618,-0.295169,-0.506661,-0.268946,-0.403568,-0.320117,-0.466931,-0.289946,-0.373653
3,PDHX|O00330,-0.144993,0.155336,0.050900,0.079455,-0.021996,-0.071422,0.081380,0.089962,0.058278,...,-0.132236,-0.095648,-0.145319,0.016944,0.065491,0.135842,0.147856,-0.020226,0.083475,0.047506
4,APIP|Q96GX9,0.145339,-0.417854,-0.843172,0.577196,-1.468350,0.221551,-0.136442,-0.323159,0.976332,...,0.713746,-0.831854,0.236361,-0.814508,-0.009136,-1.053596,-0.009197,-1.010743,-0.467762,0.403568
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8812,S1PR5|Q9H228,0.505338,0.391576,-0.219065,-0.239153,0.426485,-0.055620,-0.359028,0.013233,NaN,...,0.560319,0.031164,-0.026439,0.217259,0.358087,-0.165559,-0.033307,-0.419110,-0.010325,-0.054859
8813,GIGYF2|Q6Y7W6,-0.449736,-0.411664,-0.432484,-0.488819,-0.458550,-0.421006,-0.526388,-0.527799,-0.554216,...,-0.482969,-0.416386,-0.507107,-0.374713,-0.455986,-0.407432,-0.529108,-0.483092,-0.439813,-0.469659
8814,YME1L1|Q96TA2,0.462210,0.035486,0.035512,-0.117947,0.494874,-0.018295,-0.081191,-0.002421,-0.047577,...,0.277916,-0.021786,0.104153,0.092986,0.206298,-0.137310,-0.037395,-0.114052,0.053101,-0.077162
8815,PPP1R3F|Q6ZSY5,-0.177028,-0.080174,-0.145297,0.049689,-0.064137,-2.274703,0.017258,-0.120344,0.063776,...,-0.264418,-0.035055,-0.124822,-0.035162,-0.159635,-0.145910,-0.093056,-0.001350,-0.129813,-0.086022
8816,CACNG4|Q9UBN1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.075949,0.111414,0.132279,-0.117680,0.437808,0.240843,0.034081,0.051218,0.090312,-0.070310

In [22]:
protein.iloc[:, 0] = protein.iloc[:, 0].str.split('|').str[0]
protein.columns = ['gene_name'] + protein.columns[1:].tolist()
protein

,gene_name,b01.127C,b01.127N,b01.128C,b01.128N,b01.129C,b01.129N,b01.130C,b01.130N,b02.127C,...,b49.130C,b49.130N,b50.127C,b50.127N,b50.128C,b50.128N,b50.129C,b50.129N,b50.130C,b50.130N
0,VAMP1,-0.278255,0.410722,-0.112329,-0.162641,-0.071647,0.117440,-0.042157,0.187085,-0.835022,...,-0.073641,0.081353,0.084443,-0.220764,0.231834,-0.076819,-0.130791,-0.173961,-0.043709,-0.054343
1,KCTD13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.225794,0.019362,0.393129,0.238450,-0.039415,0.313539,0.335718,0.197204
2,TXNDC12,-0.366508,-0.498610,-0.276421,-0.354865,-0.238212,-0.321546,-0.213956,-0.532379,-0.742539,...,-0.521676,-0.289618,-0.295169,-0.506661,-0.268946,-0.403568,-0.320117,-0.466931,-0.289946,-0.373653
3,PDHX,-0.144993,0.155336,0.050900,0.079455,-0.021996,-0.071422,0.081380,0.089962,0.058278,...,-0.132236,-0.095648,-0.145319,0.016944,0.065491,0.135842,0.147856,-0.020226,0.083475,0.047506
4,APIP,0.145339,-0.417854,-0.843172,0.577196,-1.468350,0.221551,-0.136442,-0.323159,0.976332,...,0.713746,-0.831854,0.236361,-0.814508,-0.009136,-1.053596,-0.009197,-1.010743,-0.467762,0.403568
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8812,S1PR5,0.505338,0.391576,-0.219065,-0.239153,0.426485,-0.055620,-0.359028,0.013233,NaN,...,0.560319,0.031164,-0.026439,0.217259,0.358087,-0.165559,-0.033307,-0.419110,-0.010325,-0.054859
8813,GIGYF2,-0.449736,-0.411664,-0.432484,-0.488819,-0.458550,-0.421006,-0.526388,-0.527799,-0.554216,...,-0.482969,-0.416386,-0.507107,-0.374713,-0.455986,-0.407432,-0.529108,-0.483092,-0.439813,-0.469659
8814,YME1L1,0.462210,0.035486,0.035512,-0.117947,0.494874,-0.018295,-0.081191,-0.002421,-0.047577,...,0.277916,-0.021786,0.104153,0.092986,0.206298,-0.137310,-0.037395,-0.114052,0.053101,-0.077162
8815,PPP1R3F,-0.177028,-0.080174,-0.145297,0.049689,-0.064137,-2.274703,0.017258,-0.120344,0.063776,...,-0.264418,-0.035055,-0.124822,-0.035162,-0.159635,-0.145910,-0.093056,-0.001350,-0.129813,-0.086022
8816,CACNG4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.075949,0.111414,0.132279,-0.117680,0.437808,0.240843,0.034081,0.051218,0.090312,-0.070310

In [23]:
#calculate the NaN proportion of each row
nan_proportions = protein.isna().mean(axis=1)
# Display the results
print(nan_proportions)

0       0.000000
1       0.458853
2       0.000000
3       0.000000
4       0.019950
          ...
8812    0.159601
8813    0.000000
8814    0.000000
8815    0.000000
8816    0.438903
Length: 8817, dtype: float64

In [24]:
# Fill NaN values with 0 in the remaining rows
# protein = protein[nan_proportions <= 1/3]
protein = protein.groupby('gene_name', as_index=False).mean()
protein = protein.fillna(0)
protein

,gene_name,b01.127C,b01.127N,b01.128C,b01.128N,b01.129C,b01.129N,b01.130C,b01.130N,b02.127C,...,b49.130C,b49.130N,b50.127C,b50.127N,b50.128C,b50.128N,b50.129C,b50.129N,b50.130C,b50.130N
0,0,0.056825,-0.191644,0.329755,-0.105563,0.065585,-0.003961,0.068675,0.624928,0.488592,...,0.208725,-0.058407,-0.238951,-0.082743,0.131467,-0.177005,0.027383,-0.132419,-0.119505,0.101175
1,A1BG,0.078637,-0.300053,0.241096,-0.696597,0.089856,-0.891969,-0.121492,-0.674060,-0.360159,...,0.018837,-0.157993,-0.359336,-0.013279,-0.265634,-0.247393,-0.237626,-0.201277,0.146902,-0.027162
2,A2M,0.024694,-0.636475,-0.028690,-0.582275,-0.084713,-0.661039,-0.127533,-0.136789,0.071652,...,0.199730,-0.142154,-0.202204,0.249200,-0.125857,-0.223538,-0.155823,-0.227838,0.267179,0.201879
3,AAAS,-0.233335,-0.130781,-0.255823,-0.217027,-0.153392,-0.093743,-0.059018,-0.028069,-0.424658,...,-0.131372,-0.143658,0.001387,-0.216282,-0.055581,-0.137365,-0.114133,-0.164167,-0.251599,-0.204984
4,AACS,-0.628114,0.565258,-0.414934,0.312393,-0.035785,0.073530,0.376492,0.143698,-0.303845,...,0.111698,0.113708,0.110016,0.089854,0.144114,0.233087,0.140215,0.071328,-0.076422,-0.218106
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8247,ZW10,-0.197293,0.005219,-0.214280,-0.044056,-0.040142,-0.132064,-0.103338,-0.061988,0.342361,...,-0.097979,-0.138800,-0.128826,-0.173144,-0.041287,-0.075898,-0.086471,-0.158522,-0.096213,-0.051069
8248,ZYG11B,-0.252162,0.008941,-0.085900,-0.106210,-0.172175,-0.027401,-0.167308,-0.051284,-0.180830,...,-0.154005,-0.115725,-0.101206,-0.147403,-0.108262,-0.172407,-0.214812,-0.051132,-0.082856,-0.043790
8249,ZYX,0.410138,0.519709,0.439445,0.243174,0.210981,0.235149,0.297345,0.214159,0.008757,...,0.283333,0.228445,0.224010,0.288499,0.331679,0.267056,0.402636,0.243234,0.256104,0.083366
8250,ZZEF1,0.048636,0.137780,-0.018630,0.079965,0.200536,0.018601,0.052656,0.092258,0.133819,...,0.034985,-0.021704,0.084270,0.017890,0.099436,0.039346,0.021192,0.042612,0.072650,0.096722
8251,uncharacterized,-0.435451,-0.077959,-0.448560,-0.175047,-0.368123,-0.207729,-0.378900,-0.116765,-0.144452,...,-0.395805,-0.269467,-0.347543,-0.228417,-0.142008,-0.428470,-0.324132,-0.302110,-0.291100,-0.169623

### 2.6 Read Genome Variants data

In [25]:
cnv_data = pd.read_csv('./ROSMAP-raw/GenomeVariants/ROSMAP.CNV.Matrix.txt',sep='\t')
cnv_data

,CHROM,START,END,NAME,SVTYPE,Quality,SM-CTDSC,SM-CJGMZ,SM-CJFM3,SM-CTEET,...,SM-CTDVK,SM-CTED3,SM-CJK4V,SM-CJK5F,SM-CJIY9,SM-CTDQZ,SM-CJIY3,SM-CTEN7,SM-CJGH9,SM-CTEFP
0,1,766593,769113,mCNV39,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
1,1,776769,791879,mCNV40,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
2,1,830676,834492,mCNV42,mCNV,Consensus.III,2,2,2,2,...,2,2,1,2,2,2,2,2,2,2
3,1,1139154,1140550,mCNV53,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
4,1,1238076,1239491,mCNV57,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9897,22,49765259,49767008,mCNV48272,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,2,1,2,2
9898,22,49780301,49781900,DUP48274,DUP,Consensus.III,3,3,4,3,...,3,4,3,2,4,3,4,3,3,3
9899,22,49840021,49908322,mCNV48276,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
9900,22,51082701,51121100,mCNV48291,mCNV,Consensus.III,2,2,2,2,...,2,2,1,2,2,2,2,2,2,2
9901,22,51119846,51121237,mCNV48292,mCNV,Consensus.III,1,3,2,3,...,3,3,1,1,2,1,3,1,2,3

In [26]:
ensembl_data = EnsemblRelease()
ensembl_data.download()
ensembl_data.index()

INFO:pyensembl.sequence_data:Loaded sequence dictionary from C:\Users\Lilab\AppData\Local\pyensembl\GRCh38\ensembl110\pyensembl\GRCh38\ensembl110\Cache\Homo_sapiens.GRCh38.cdna.all.fa.gz.pickle
INFO:pyensembl.sequence_data:Loaded sequence dictionary from C:\Users\Lilab\AppData\Local\pyensembl\GRCh38\ensembl110\pyensembl\GRCh38\ensembl110\Cache\Homo_sapiens.GRCh38.ncrna.fa.gz.pickle
INFO:pyensembl.sequence_data:Loaded sequence dictionary from C:\Users\Lilab\AppData\Local\pyensembl\GRCh38\ensembl110\pyensembl\GRCh38\ensembl110\Cache\Homo_sapiens.GRCh38.pep.all.fa.gz.pickle

In [27]:
# use pyensemb to map the gene name
def get_gene_names(chromosome, start, end):
    genes = ensembl_data.genes_at_locus(contig=chromosome, position=start, end=end)
    gene_names = [gene.gene_name for gene in genes]
    return ', '.join(gene_names) if gene_names else None

# Apply the function to each row in the DataFrame
cnv_data['gene_name'] = cnv_data.apply(
    lambda row: get_gene_names(str(row['CHROM']), row['START'], row['END']), axis=1
)
cnv_data

,CHROM,START,END,NAME,SVTYPE,Quality,SM-CTDSC,SM-CJGMZ,SM-CJFM3,SM-CTEET,...,SM-CTED3,SM-CJK4V,SM-CJK5F,SM-CJIY9,SM-CTDQZ,SM-CJIY3,SM-CTEN7,SM-CJGH9,SM-CTEFP,gene_name
0,1,766593,769113,mCNV39,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,2,2,2,", ,"
1,1,776769,791879,mCNV40,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,2,2,2,", LINC01409, ,"
2,1,830676,834492,mCNV42,mCNV,Consensus.III,2,2,2,2,...,2,1,2,2,2,2,2,2,2,LINC01128
3,1,1139154,1140550,mCNV53,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,2,2,2,LINC01342
4,1,1238076,1239491,mCNV57,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,2,2,2,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9897,22,49765259,49767008,mCNV48272,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,1,2,2,None
9898,22,49780301,49781900,DUP48274,DUP,Consensus.III,3,3,4,3,...,4,3,2,4,3,4,3,3,3,BRD1
9899,22,49840021,49908322,mCNV48276,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,2,2,2,"ZBED4, ALG12, , , Metazoa_SRP,"
9900,22,51082701,51121100,mCNV48291,mCNV,Consensus.III,2,2,2,2,...,2,1,2,2,2,2,2,2,2,None
9901,22,51119846,51121237,mCNV48292,mCNV,Consensus.III,1,3,2,3,...,3,1,1,2,1,3,1,2,3,None

In [28]:
# Function to clean gene names
def clean_gene_names(gene_names):
    if gene_names:
        # Split the string by comma, strip whitespace and periods, then filter out empty strings
        genes = [gene.strip(' .') for gene in gene_names.split(',') if gene.strip(' .')]
        # Join the cleaned gene names with a comma
        return ', '.join(genes)
    else:
        # If gene_names is None or empty, return a placeholder
        return 'No gene found'

# Apply the function to clean up the gene names
cnv_data['gene_name'] = cnv_data['gene_name'].apply(clean_gene_names)
cnv_data

,CHROM,START,END,NAME,SVTYPE,Quality,SM-CTDSC,SM-CJGMZ,SM-CJFM3,SM-CTEET,...,SM-CTED3,SM-CJK4V,SM-CJK5F,SM-CJIY9,SM-CTDQZ,SM-CJIY3,SM-CTEN7,SM-CJGH9,SM-CTEFP,gene_name
0,1,766593,769113,mCNV39,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,2,2,2,
1,1,776769,791879,mCNV40,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,2,2,2,LINC01409
2,1,830676,834492,mCNV42,mCNV,Consensus.III,2,2,2,2,...,2,1,2,2,2,2,2,2,2,LINC01128
3,1,1139154,1140550,mCNV53,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,2,2,2,LINC01342
4,1,1238076,1239491,mCNV57,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,2,2,2,No gene found
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9897,22,49765259,49767008,mCNV48272,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,1,2,2,No gene found
9898,22,49780301,49781900,DUP48274,DUP,Consensus.III,3,3,4,3,...,4,3,2,4,3,4,3,3,3,BRD1
9899,22,49840021,49908322,mCNV48276,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,2,2,2,"ZBED4, ALG12, Metazoa_SRP"
9900,22,51082701,51121100,mCNV48291,mCNV,Consensus.III,2,2,2,2,...,2,1,2,2,2,2,2,2,2,No gene found
9901,22,51119846,51121237,mCNV48292,mCNV,Consensus.III,1,3,2,3,...,3,1,1,2,1,3,1,2,3,No gene found

In [29]:
cnv_data['gene_name'] = cnv_data['gene_name'].str.split(', ')
cnv_data_exploded = cnv_data.explode('gene_name')
cnv_data_exploded

,CHROM,START,END,NAME,SVTYPE,Quality,SM-CTDSC,SM-CJGMZ,SM-CJFM3,SM-CTEET,...,SM-CTED3,SM-CJK4V,SM-CJK5F,SM-CJIY9,SM-CTDQZ,SM-CJIY3,SM-CTEN7,SM-CJGH9,SM-CTEFP,gene_name
0,1,766593,769113,mCNV39,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,2,2,2,
1,1,776769,791879,mCNV40,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,2,2,2,LINC01409
2,1,830676,834492,mCNV42,mCNV,Consensus.III,2,2,2,2,...,2,1,2,2,2,2,2,2,2,LINC01128
3,1,1139154,1140550,mCNV53,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,2,2,2,LINC01342
4,1,1238076,1239491,mCNV57,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,2,2,2,No gene found
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9899,22,49840021,49908322,mCNV48276,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,2,2,2,ZBED4
9899,22,49840021,49908322,mCNV48276,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,2,2,2,ALG12
9899,22,49840021,49908322,mCNV48276,mCNV,Consensus.III,2,2,2,2,...,2,2,2,2,2,2,2,2,2,Metazoa_SRP
9900,22,51082701,51121100,mCNV48291,mCNV,Consensus.III,2,2,2,2,...,2,1,2,2,2,2,2,2,2,No gene found
9901,22,51119846,51121237,mCNV48292,mCNV,Consensus.III,1,3,2,3,...,3,1,1,2,1,3,1,2,3,No gene found

In [30]:
# Filter out rows with empty 'Gene_Names' or 'No gene found'
cnv_data_exploded = cnv_data_exploded[(cnv_data_exploded['gene_name'] != '') & (cnv_data_exploded['gene_name'] != 'No gene found')]

sample_columns = cnv_data_exploded.columns[6:-1] 
cnv_aggregated = cnv_data_exploded.groupby(['gene_name','SVTYPE'])[sample_columns].sum().reset_index()
# cnv_aggregated = cnv_data_exploded.groupby('gene_name')[sample_columns].sum().reset_index()
cnv_aggregated

,gene_name,SVTYPE,SM-CTDSC,SM-CJGMZ,SM-CJFM3,SM-CTEET,SM-CJK4L,SM-CJIZ4,SM-CJK3I,SM-CJGN4,...,SM-CTDVK,SM-CTED3,SM-CJK4V,SM-CJK5F,SM-CJIY9,SM-CTDQZ,SM-CJIY3,SM-CTEN7,SM-CJGH9,SM-CTEFP
0,5S_rRNA,DEL,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
1,5S_rRNA,DUP,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
2,A2ML1-AS1,DEL,2,2,2,2,2,2,2,2,...,2,2,1,2,2,2,2,2,2,2
3,A4GALT,mCNV,2,3,2,3,2,3,2,3,...,2,3,2,2,2,2,2,1,3,3
4,AAAS,mCNV,2,2,2,2,2,2,2,2,...,2,2,1,2,2,2,1,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7300,ZSWIM6,DEL,2,2,2,2,2,2,2,2,...,2,2,2,1,2,2,2,2,2,2
7301,ZSWIM9,mCNV,6,6,6,6,6,6,6,5,...,6,6,3,3,5,6,3,6,6,6
7302,ZUP1,mCNV,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
7303,ZZZ3,DEL,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
7304,hsa-mir-423,mCNV,2,2,2,2,2,2,2,1,...,2,2,1,1,1,2,1,2,2,2

In [31]:
cnv_aggregated_del = cnv_aggregated[cnv_aggregated['SVTYPE'] == 'DEL']
cnv_aggregated_dup = cnv_aggregated[cnv_aggregated['SVTYPE'] == 'DUP']
cnv_aggregated_mcnv = cnv_aggregated[cnv_aggregated['SVTYPE'] == 'mCNV']
print(f"Shape of cnv_aggregated_del: {cnv_aggregated_del.shape}")
print(f"Shape of cnv_aggregated_dup: {cnv_aggregated_dup.shape}")
print(f"Shape of cnv_aggregated_mcnv: {cnv_aggregated_mcnv.shape}")

Shape of cnv_aggregated_del: (2483, 1129)
Shape of cnv_aggregated_dup: (1096, 1129)
Shape of cnv_aggregated_mcnv: (3726, 1129)

In [32]:
# Create a DataFrame from the union set of all gene names
cnv_all_genes = pd.DataFrame({'gene_name': list(set(cnv_aggregated_del['gene_name']).union(set(cnv_aggregated_dup['gene_name']), set(cnv_aggregated_mcnv['gene_name'])))})

# Merge each aggregated DataFrame with the all genes DataFrame
# This will align all genes across all DataFrames, and fill missing entries with 0
cnv_aggregated_del = pd.merge(cnv_all_genes, cnv_aggregated_del, on='gene_name', how='outer').fillna(-1)
cnv_aggregated_dup = pd.merge(cnv_all_genes, cnv_aggregated_dup, on='gene_name', how='outer').fillna(-1)
cnv_aggregated_mcnv = pd.merge(cnv_all_genes, cnv_aggregated_mcnv, on='gene_name', how='outer').fillna(-1)

# Drop the 'SVTYPE' column from each merged DataFrame
cnv_aggregated_del.drop(columns='SVTYPE', inplace=True)
cnv_aggregated_dup.drop(columns='SVTYPE', inplace=True)
cnv_aggregated_mcnv.drop(columns='SVTYPE', inplace=True)
print(f"Shape of cnv_aggregated_del: {cnv_aggregated_del.shape}")
print(f"Shape of cnv_aggregated_dup: {cnv_aggregated_dup.shape}")
print(f"Shape of cnv_aggregated_mcnv: {cnv_aggregated_mcnv.shape}")

Shape of cnv_aggregated_del: (6423, 1128)
Shape of cnv_aggregated_dup: (6423, 1128)
Shape of cnv_aggregated_mcnv: (6423, 1128)

In [33]:
cnv_aggregated_del

,gene_name,SM-CTDSC,SM-CJGMZ,SM-CJFM3,SM-CTEET,SM-CJK4L,SM-CJIZ4,SM-CJK3I,SM-CJGN4,SM-CTDSM,...,SM-CTDVK,SM-CTED3,SM-CJK4V,SM-CJK5F,SM-CJIY9,SM-CTDQZ,SM-CJIY3,SM-CTEN7,SM-CJGH9,SM-CTEFP
0,MRPL45,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
1,MANCR,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
2,CCDC68,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,2.0,0.0,2.0,1.0,0.0,0.0,1.0,0.0
3,HIF1AP1,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
4,SRRM3,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6418,RTBDN,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
6419,TM4SF19-DYNLT2B,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
6420,OR52H1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
6421,SAMD3,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
6422,POLR2F,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0

In [34]:
# cnv_aggregated.iloc[:, 1:] = cnv_aggregated.iloc[:, 1:].where(cnv_aggregated.iloc[:, 1:] == 0, 1)
# cnv_aggregated

In [35]:
# snphead = pd.read_csv('./ROSMAP-raw/GenomeVariants/SNP-Array-raw/AMP-AD_ROSMAP_Rush-Broad_AffymetrixGenechip6_Imputed.fam', sep='\t',header=None)
# snphead

In [36]:
# survival_gwas_id = pd.DataFrame(survival.iloc[:, 1].astype(str) + survival.iloc[:, 0].astype(str), columns=['gwas_id'])
# survival_gwas_id['individualID'] = survival['individualID']

# # Displaying the new DataFrame
# survival_gwas_id

In [37]:
# gwas_id_list = survival_gwas_id['gwas_id'].tolist()

# snphead['extracted_gwas_id'] = snphead.iloc[:, 0].apply(
#     lambda x: next((gwas_id for gwas_id in gwas_id_list if gwas_id in x), np.nan)
# )

# # Perform a left merge with 'survival_gwas_id' on the extracted 'gwas_id' to keep all rows from 'snphead'
# # and to get the corresponding 'individualID' where there is a match
# merged_result = pd.merge(
#     snphead, 
#     survival_gwas_id, 
#     how='left', 
#     left_on='extracted_gwas_id', 
#     right_on='gwas_id'
# )

# # Select only the 'gwas_id' and 'individualID' columns for the final result
# # Fill missing values with 'NA' to indicate unmatched rows
# snphead_updated = merged_result[['gwas_id', 'individualID']].fillna('NA')

# # Display the head of the final DataFrame
# snphead_updated

In [38]:
# snphead_updated_withoutNA = snphead_updated[snphead_updated.iloc[:, 0] != "NA"]
# snphead_updated_withoutNA

## 3.Methylation data process

### 3.1 Define methylation region

In [39]:
import pandas as pd
import numpy as np

#Define vectorized area determination function for methylation data
def vectorized_determine_region(distances):
    regions = ['Upstream', 'Distal Promoter', 'Proximal Promoter', 'Core Promoter', 'Downstream']
    conditions = [
        (-6000 <= distances) & (distances < -3000),
        (-3000 <= distances) & (distances < -250),
        (-250 <= distances) & (distances < -50),
        (-50 <= distances) & (distances <= 0),
        (0 < distances) & (distances <= 3000)
    ]
    return np.select(conditions, regions, default=None)

### 3.2 Merge the annotation files to the methylation data and apply region function

In [40]:
# Merging basic data and methylation data
methylation_merged_df = pd.merge(map_annotation, methylation_value, left_on='ID', right_on='TargetID', how='right')

# Determining the region for each row outside the loop
methylation_merged_df['Region'] = vectorized_determine_region(methylation_merged_df['Distance_closest_TSS'])

methylation_merged_df = methylation_merged_df.dropna(subset=['Region'])  # Remove rows without a region

# Initializing a dictionary to store data for each region
regions_data = {region: pd.DataFrame() for region in ["Upstream", "Distal Promoter", "Proximal Promoter", "Core Promoter", "Downstream"]}

In [41]:
methylation_merged_df

,ID,Closest_TSS,Closest_TSS_gene_name,Distance_closest_TSS,TargetID,TBI-AUTO73325-PT-3149,PT-BZHL,PT-BZCH,PT-BY9H,TBI-AUTO73307-PT-314I,...,TBI-AUTO73291-PT-35OD,PT-BZD7,PT-BZG8,PT-C1N8,PT-BYJP,PT-BZHV,PT-BZI2,TBI-AUTO73257-PT-35OE,PT-BZD3,Region
3,cg00001349,166958518,MAEL,-79.0,cg00001349,0.865488,0.919570,0.882256,0.902912,0.907610,...,0.900684,0.906257,0.756173,0.948341,0.904996,0.927201,0.856637,0.917827,0.943320,Proximal Promoter
5,cg00001446,43833698,ELOVL1,2658.0,cg00001446,0.842025,0.831457,0.835075,0.834157,0.839395,...,0.847344,0.825179,0.887574,0.881636,0.852642,0.833056,0.842108,0.841747,0.833336,Downstream
7,cg00001583,200011716,NR5A2,70.0,cg00001583,0.099888,0.076240,0.075861,0.101837,0.071947,...,0.084641,0.092234,0.066651,0.040554,0.059607,0.116837,0.069391,0.061016,0.035535,Downstream
8,cg00001593,170489886,AK096329,-547.0,cg00001593,0.918081,0.955305,0.896318,0.941423,0.940628,...,0.918949,0.929937,0.952355,0.968486,0.972349,0.944855,0.924879,0.885508,0.939249,Distal Promoter
9,cg00002028,20959947,PINK1,63.0,cg00002028,0.026821,0.035839,0.020016,0.014101,0.031390,...,0.021462,0.033637,0.024296,0.033715,0.019535,0.011352,0.020888,0.035047,0.026995,Downstream
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420108,cg27652464,48885287,FAM19A5,1488.0,cg27652464,0.077791,0.081391,0.066050,0.076101,0.081930,...,0.082855,0.078940,0.033035,0.029362,0.041915,0.059740,0.060660,0.040806,0.044582,Downstream
420111,cg27657537,20862338,MED15,1424.0,cg27657537,0.246730,0.273854,0.250933,0.297172,0.256656,...,0.296850,0.295459,0.266729,0.301941,0.265106,0.263730,0.268427,0.252280,0.243976,Downstream
420112,cg27662611,38599026,MAFF,-45.0,cg27662611,0.091869,0.098040,0.066290,0.094694,0.069012,...,0.080595,0.067712,0.072670,0.069177,0.084736,0.071235,0.072670,0.083982,0.062013,Core Promoter
420113,cg27665648,30116343,CABP7,-3940.0,cg27665648,0.680242,0.683700,0.662226,0.711880,0.699262,...,0.606769,0.694081,0.700518,0.710467,0.697145,0.675443,0.671625,0.682511,0.718816,Upstream
420120,ch.22.439136F,32113276,PRR14L,1202.0,ch.22.439136F,0.066196,0.074446,0.083344,0.051879,0.046465,...,0.059595,0.075262,0.083866,0.065719,0.092159,0.064988,0.074380,0.047593,0.058276,Downstream

In [42]:
original_gene_names = methylation_merged_df['Closest_TSS_gene_name'].copy()

# Use a regular expression to remove the period and any characters following it
methylation_merged_df['Closest_TSS_gene_name'] = methylation_merged_df['Closest_TSS_gene_name'].str.replace(r'\..*', '', regex=True)

# Determine how many rows were changed by comparing the new values to the original ones
rows_changed = (original_gene_names != methylation_merged_df['Closest_TSS_gene_name']).sum()

# Output the updated DataFrame and the number of rows that were changed
methylation_merged_df, rows_changed

(                   ID Closest_TSS Closest_TSS_gene_name  Distance_closest_TSS  \
 3          cg00001349   166958518                  MAEL                 -79.0
 5          cg00001446    43833698                ELOVL1                2658.0
 7          cg00001583   200011716                 NR5A2                  70.0
 8          cg00001593   170489886              AK096329                -547.0
 9          cg00002028    20959947                 PINK1                  63.0
 ...               ...         ...                   ...                   ...
 420108     cg27652464    48885287               FAM19A5                1488.0
 420111     cg27657537    20862338                 MED15                1424.0
 420112     cg27662611    38599026                  MAFF                 -45.0
 420113     cg27665648    30116343                 CABP7               -3940.0
 420120  ch.22.439136F    32113276                PRR14L                1202.0

              TargetID  TBI-AUTO73325-PT-3149   PT-BZHL   PT-BZCH   PT-BY9H  \
 3          cg00001349               0.865488  0.919570  0.882256  0.902912
 5          cg00001446               0.842025  0.831457  0.835075  0.834157
 7          cg00001583               0.099888  0.076240  0.075861  0.101837
 8          cg00001593               0.918081  0.955305  0.896318  0.941423
 9          cg00002028               0.026821  0.035839  0.020016  0.014101
 ...               ...                    ...       ...       ...       ...
 420108     cg27652464               0.077791  0.081391  0.066050  0.076101
 420111     cg27657537               0.246730  0.273854  0.250933  0.297172
 420112     cg27662611               0.091869  0.098040  0.066290  0.094694
 420113     cg27665648               0.680242  0.683700  0.662226  0.711880
 420120  ch.22.439136F               0.066196  0.074446  0.083344  0.051879

         TBI-AUTO73307-PT-314I  ...  TBI-AUTO73291-PT-35OD   PT-BZD7   PT-BZG8  \
 3                    0.907610  ...               0.900684  0.906257  0.756173
 5                    0.839395  ...               0.847344  0.825179  0.887574
 7                    0.071947  ...               0.084641  0.092234  0.066651
 8                    0.940628  ...               0.918949  0.929937  0.952355
 9                    0.031390  ...               0.021462  0.033637  0.024296
 ...                       ...  ...                    ...       ...       ...
 420108               0.081930  ...               0.082855  0.078940  0.033035
 420111               0.256656  ...               0.296850  0.295459  0.266729
 420112               0.069012  ...               0.080595  0.067712  0.072670
 420113               0.699262  ...               0.606769  0.694081  0.700518
 420120               0.046465  ...               0.059595  0.075262  0.083866

          PT-C1N8   PT-BYJP   PT-BZHV   PT-BZI2  TBI-AUTO73257-PT-35OE  \
 3       0.948341  0.904996  0.927201  0.856637               0.917827
 5       0.881636  0.852642  0.833056  0.842108               0.841747
 7       0.040554  0.059607  0.116837  0.069391               0.061016
 8       0.968486  0.972349  0.944855  0.924879               0.885508
 9       0.033715  0.019535  0.011352  0.020888               0.035047
 ...          ...       ...       ...       ...                    ...
 420108  0.029362  0.041915  0.059740  0.060660               0.040806
 420111  0.301941  0.265106  0.263730  0.268427               0.252280
 420112  0.069177  0.084736  0.071235  0.072670               0.083982
 420113  0.710467  0.697145  0.675443  0.671625               0.682511
 420120  0.065719  0.092159  0.064988  0.074380               0.047593

          PT-BZD3             Region
 3       0.943320  Proximal Promoter
 5       0.833336         Downstream
 7       0.035535         Downstream
 8       0.939249    Distal Promoter
 9       0.026995         Downstream
 ...          ...                ...
 420108  0.044582         Downstream
 420111  0.243976         Downstream
 420112  0.062013      Core Promoter
 420113  0.718816           Upstream
 420120  0.058276         Downstream

 [249506 rows x 746 columns],
 65)

In [43]:
# Delete the 'sample' column
methylation_merged_df = methylation_merged_df.drop('TargetID', axis=1)
# Delete the 'ID' column
methylation_merged_df = methylation_merged_df.drop('ID', axis=1)
# Delete the 'Distance_closest_TSS' column
methylation_merged_df = methylation_merged_df.drop('Distance_closest_TSS', axis=1)

In [44]:
methylation_merged_df

,Closest_TSS,Closest_TSS_gene_name,TBI-AUTO73325-PT-3149,PT-BZHL,PT-BZCH,PT-BY9H,TBI-AUTO73307-PT-314I,TBI-AUTO73043-PT-35BD,PT-BZI5,PT-BZ1A,...,TBI-AUTO73291-PT-35OD,PT-BZD7,PT-BZG8,PT-C1N8,PT-BYJP,PT-BZHV,PT-BZI2,TBI-AUTO73257-PT-35OE,PT-BZD3,Region
3,166958518,MAEL,0.865488,0.919570,0.882256,0.902912,0.907610,0.897496,0.939212,0.919514,...,0.900684,0.906257,0.756173,0.948341,0.904996,0.927201,0.856637,0.917827,0.943320,Proximal Promoter
5,43833698,ELOVL1,0.842025,0.831457,0.835075,0.834157,0.839395,0.842799,0.850811,0.842074,...,0.847344,0.825179,0.887574,0.881636,0.852642,0.833056,0.842108,0.841747,0.833336,Downstream
7,200011716,NR5A2,0.099888,0.076240,0.075861,0.101837,0.071947,0.036712,0.041233,0.083998,...,0.084641,0.092234,0.066651,0.040554,0.059607,0.116837,0.069391,0.061016,0.035535,Downstream
8,170489886,AK096329,0.918081,0.955305,0.896318,0.941423,0.940628,0.930346,0.944459,0.977162,...,0.918949,0.929937,0.952355,0.968486,0.972349,0.944855,0.924879,0.885508,0.939249,Distal Promoter
9,20959947,PINK1,0.026821,0.035839,0.020016,0.014101,0.031390,0.022777,0.031833,0.014578,...,0.021462,0.033637,0.024296,0.033715,0.019535,0.011352,0.020888,0.035047,0.026995,Downstream
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420108,48885287,FAM19A5,0.077791,0.081391,0.066050,0.076101,0.081930,0.035654,0.070314,0.065970,...,0.082855,0.078940,0.033035,0.029362,0.041915,0.059740,0.060660,0.040806,0.044582,Downstream
420111,20862338,MED15,0.246730,0.273854,0.250933,0.297172,0.256656,0.273096,0.278133,0.267989,...,0.296850,0.295459,0.266729,0.301941,0.265106,0.263730,0.268427,0.252280,0.243976,Downstream
420112,38599026,MAFF,0.091869,0.098040,0.066290,0.094694,0.069012,0.100561,0.103787,0.059369,...,0.080595,0.067712,0.072670,0.069177,0.084736,0.071235,0.072670,0.083982,0.062013,Core Promoter
420113,30116343,CABP7,0.680242,0.683700,0.662226,0.711880,0.699262,0.738775,0.720822,0.667222,...,0.606769,0.694081,0.700518,0.710467,0.697145,0.675443,0.671625,0.682511,0.718816,Upstream
420120,32113276,PRR14L,0.066196,0.074446,0.083344,0.051879,0.046465,0.075939,0.091995,0.039107,...,0.059595,0.075262,0.083866,0.065719,0.092159,0.064988,0.074380,0.047593,0.058276,Downstream

In [45]:
methylation_merged_df['Closest_TSS'] = methylation_merged_df['Closest_TSS'].astype(int)
methylation_merged_df['Closest_TSS_gene_name'] = methylation_merged_df['Closest_TSS_gene_name'].astype(str)
methylation_merged_df['Region'] = methylation_merged_df['Region'].astype(str)

In [46]:
print(methylation_merged_df[['Closest_TSS', 'Closest_TSS_gene_name', 'Region']].dtypes)

Closest_TSS               int32
Closest_TSS_gene_name    object
Region                   object
dtype: object

### 3.3 Calculate the average methylation value of five regions

In [47]:
# obtain all regions
regions = methylation_merged_df['Region'].unique()
regions

array(['Proximal Promoter', 'Downstream', 'Distal Promoter',
       'Core Promoter', 'Upstream'], dtype=object)

In [48]:
import pandas as pd
# Initialize empty DataFrames for each region
Upstream_df = pd.DataFrame()
Distal_Promoter_df = pd.DataFrame()
Proximal_Promoter_df = pd.DataFrame()
Core_Promoter_df = pd.DataFrame()
Downstream_df = pd.DataFrame()

# Operate on each region
for region in regions:
    # Get all data for this region
    region_data = methylation_merged_df[methylation_merged_df['Region'] == region]
    
    # Group and calculate the average for each (TSS, Region) combination
    grouped = region_data.groupby(['Closest_TSS_gene_name', 'Region'], as_index=False).mean()
    
    # Since we split the data into different files based on Region, we can delete this column
    grouped = grouped.drop(columns=['Region'])
    
    # Print the shape of the grouped data
    print(f"Shape of {region}: {grouped.shape}")
    
    # Assign the grouped data to the respective DataFrame
    if region == 'Upstream':
        Upstream_df = grouped
    elif region == 'Distal Promoter':
        Distal_Promoter_df = grouped
    elif region == 'Proximal Promoter':
        Proximal_Promoter_df = grouped
    elif region == 'Core Promoter':
        Core_Promoter_df = grouped
    elif region == 'Downstream':
        Downstream_df = grouped

    # Optionally, save the data for this region to a new csv file
    # grouped.to_csv(f"{region}_averaged_tss_data.csv", index=False)

Shape of Proximal Promoter: (15812, 742)
Shape of Downstream: (20577, 742)
Shape of Distal Promoter: (18238, 742)
Shape of Core Promoter: (9871, 742)
Shape of Upstream: (7128, 742)

### 3.4 Unify gene and TSS for five methylation value files

In [49]:
import pandas as pd

# from methylation files above DataFrame 
dfs = [Upstream_df, Distal_Promoter_df, Proximal_Promoter_df, Core_Promoter_df, Downstream_df]

# merge those files to find all combos 
all_genes_tss = pd.concat(dfs)['Closest_TSS_gene_name'].drop_duplicates()

In [50]:
all_genes_tss

0            1/2-SBSRNA4
1                  40969
2                  40970
3                  40971
4                  40972
              ...
20459             ZNF791
20497             ZNF862
20506              ZNF91
20528             ZRANB2
20572    hsa-miR-3194-3p
Name: Closest_TSS_gene_name, Length: 23280, dtype: object

In [51]:
# Merge unique combinations back into each DataFrame and fill NaN values with 0
# Upstream
Upstream_df = pd.merge(all_genes_tss, Upstream_df, on=['Closest_TSS_gene_name'], how='outer').fillna(0)
print(f"Shape of Upstream_df: {Upstream_df.shape}")

# Distal Promoter
Distal_Promoter_df = pd.merge(all_genes_tss, Distal_Promoter_df, on=['Closest_TSS_gene_name'], how='outer').fillna(0)
print(f"Shape of Distal_Promoter_df: {Distal_Promoter_df.shape}")

# Proximal Promoter
Proximal_Promoter_df = pd.merge(all_genes_tss, Proximal_Promoter_df, on=['Closest_TSS_gene_name'], how='outer').fillna(0)
print(f"Shape of Proximal_Promoter_df: {Proximal_Promoter_df.shape}")

# Core Promoter
Core_Promoter_df = pd.merge(all_genes_tss, Core_Promoter_df, on=['Closest_TSS_gene_name'], how='outer').fillna(0)
print(f"Shape of Core_Promoter_df: {Core_Promoter_df.shape}")

# Downstream
Downstream_df = pd.merge(all_genes_tss, Downstream_df, on=['Closest_TSS_gene_name'], how='outer').fillna(0)
print(f"Shape of Downstream_df: {Downstream_df.shape}")

Shape of Upstream_df: (23280, 742)
Shape of Distal_Promoter_df: (23280, 742)
Shape of Proximal_Promoter_df: (23280, 742)
Shape of Core_Promoter_df: (23280, 742)
Shape of Downstream_df: (23280, 742)

In [52]:
Upstream_df.rename(columns={'Closest_TSS_gene_name': 'gene_name'}, inplace=True)
Distal_Promoter_df.rename(columns={'Closest_TSS_gene_name': 'gene_name'}, inplace=True)
Proximal_Promoter_df.rename(columns={'Closest_TSS_gene_name': 'gene_name'}, inplace=True)
Core_Promoter_df.rename(columns={'Closest_TSS_gene_name': 'gene_name'}, inplace=True)
Downstream_df.rename(columns={'Closest_TSS_gene_name': 'gene_name'}, inplace=True)

display(Upstream_df)
display(Distal_Promoter_df)
display(Proximal_Promoter_df)
display(Core_Promoter_df)
display(Downstream_df)

,gene_name,Closest_TSS,TBI-AUTO73325-PT-3149,PT-BZHL,PT-BZCH,PT-BY9H,TBI-AUTO73307-PT-314I,TBI-AUTO73043-PT-35BD,PT-BZI5,PT-BZ1A,...,TBI-AUTO72955-PT-35OC,TBI-AUTO73291-PT-35OD,PT-BZD7,PT-BZG8,PT-C1N8,PT-BYJP,PT-BZHV,PT-BZI2,TBI-AUTO73257-PT-35OE,PT-BZD3
0,1/2-SBSRNA4,110354972.0,0.931928,0.922927,0.921658,0.934680,0.950280,0.915567,0.895290,0.942072,...,0.929474,0.932108,0.909341,0.921341,0.930176,0.916491,0.913546,0.936391,0.905927,0.942917
1,40969,220960038.0,0.718230,0.698030,0.712573,0.705048,0.734309,0.771367,0.782897,0.704986,...,0.766211,0.675562,0.720371,0.689035,0.618610,0.764157,0.576607,0.754224,0.745078,0.710471
2,40970,220921675.0,0.868322,0.845299,0.849537,0.892048,0.881078,0.867949,0.886519,0.902767,...,0.874877,0.851768,0.870165,0.878390,0.893037,0.901645,0.876906,0.870745,0.852633,0.877366
3,40971,126366439.0,0.914631,0.890200,0.893712,0.904816,0.934809,0.901929,0.918363,0.889949,...,0.907466,0.905140,0.898941,0.857999,0.960562,0.964220,0.896651,0.901460,0.907702,0.936499
4,40972,217236749.0,0.689192,0.726004,0.691986,0.669473,0.690793,0.725609,0.711018,0.717188,...,0.822901,0.727588,0.706725,0.726323,0.695048,0.800269,0.685743,0.758808,0.726784,0.716149
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23275,ZNF791,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23276,ZNF862,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23277,ZNF91,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23278,ZRANB2,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23279,hsa-miR-3194-3p,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

,gene_name,Closest_TSS,TBI-AUTO73325-PT-3149,PT-BZHL,PT-BZCH,PT-BY9H,TBI-AUTO73307-PT-314I,TBI-AUTO73043-PT-35BD,PT-BZI5,PT-BZ1A,...,TBI-AUTO72955-PT-35OC,TBI-AUTO73291-PT-35OD,PT-BZD7,PT-BZG8,PT-C1N8,PT-BYJP,PT-BZHV,PT-BZI2,TBI-AUTO73257-PT-35OE,PT-BZD3
0,1/2-SBSRNA4,1.103550e+08,0.050086,0.046152,0.047936,0.047600,0.044529,0.042937,0.046128,0.036349,...,0.046718,0.050942,0.057558,0.042817,0.034843,0.049129,0.050484,0.048231,0.041461,0.035273
1,40969,1.823108e+08,0.392057,0.393938,0.374393,0.394217,0.387216,0.384722,0.399945,0.400160,...,0.387394,0.387438,0.388211,0.399827,0.391225,0.393465,0.399843,0.385534,0.397759,0.397958
2,40970,1.359443e+08,0.310090,0.305279,0.298020,0.309443,0.307445,0.316317,0.325516,0.289902,...,0.314234,0.318619,0.322369,0.331648,0.313204,0.322797,0.317953,0.311885,0.323359,0.317395
3,40971,1.263664e+08,0.405201,0.427466,0.397301,0.469572,0.417824,0.425026,0.451523,0.430546,...,0.401051,0.387067,0.409743,0.477469,0.452182,0.450699,0.406353,0.405420,0.429750,0.438600
4,40972,2.172367e+08,0.121688,0.126594,0.126133,0.134649,0.099313,0.099806,0.132725,0.135713,...,0.108077,0.124255,0.136012,0.122335,0.115328,0.124249,0.118947,0.132945,0.122179,0.122315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23275,ZNF791,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23276,ZNF862,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23277,ZNF91,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23278,ZRANB2,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23279,hsa-miR-3194-3p,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

,gene_name,Closest_TSS,TBI-AUTO73325-PT-3149,PT-BZHL,PT-BZCH,PT-BY9H,TBI-AUTO73307-PT-314I,TBI-AUTO73043-PT-35BD,PT-BZI5,PT-BZ1A,...,TBI-AUTO72955-PT-35OC,TBI-AUTO73291-PT-35OD,PT-BZD7,PT-BZG8,PT-C1N8,PT-BYJP,PT-BZHV,PT-BZI2,TBI-AUTO73257-PT-35OE,PT-BZD3
0,1/2-SBSRNA4,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,40969,1.745803e+08,0.062457,0.062992,0.060792,0.072635,0.053607,0.052409,0.078899,0.054821,...,0.056719,0.058685,0.062915,0.054353,0.047246,0.058168,0.051281,0.059223,0.063899,0.051598
2,40970,1.146999e+08,0.019823,0.016219,0.025095,0.004104,0.018158,0.023213,0.011316,0.006909,...,0.023464,0.018230,0.026458,0.016108,0.007415,0.018649,0.013601,0.015024,0.016403,0.013799
3,40971,1.263664e+08,0.053635,0.043674,0.056735,0.039288,0.056034,0.049312,0.037346,0.035949,...,0.053628,0.046762,0.060741,0.037930,0.031851,0.047490,0.048975,0.049245,0.071294,0.042729
4,40972,2.172367e+08,0.041339,0.040678,0.044696,0.046232,0.038569,0.040817,0.037882,0.040225,...,0.042183,0.044143,0.051431,0.036785,0.036056,0.040026,0.041975,0.051319,0.045344,0.036178
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23275,ZNF791,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23276,ZNF862,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23277,ZNF91,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23278,ZRANB2,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23279,hsa-miR-3194-3p,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

,gene_name,Closest_TSS,TBI-AUTO73325-PT-3149,PT-BZHL,PT-BZCH,PT-BY9H,TBI-AUTO73307-PT-314I,TBI-AUTO73043-PT-35BD,PT-BZI5,PT-BZ1A,...,TBI-AUTO72955-PT-35OC,TBI-AUTO73291-PT-35OD,PT-BZD7,PT-BZG8,PT-C1N8,PT-BYJP,PT-BZHV,PT-BZI2,TBI-AUTO73257-PT-35OE,PT-BZD3
0,1/2-SBSRNA4,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,40969,1.931322e+08,0.032889,0.022269,0.038779,0.027230,0.020263,0.024609,0.019103,0.027352,...,0.019140,0.020243,0.031096,0.014201,0.001955,0.021315,0.013171,0.026491,0.021192,0.000000
2,40970,4.388543e+07,0.010026,0.005568,0.009481,0.001321,0.005410,0.012487,0.007074,0.007051,...,0.011333,0.009509,0.009776,0.007986,0.004716,0.003443,0.005855,0.007794,0.009484,0.008447
3,40971,1.263664e+08,0.002757,0.000874,0.005387,0.000785,0.000619,0.011755,0.007571,0.002990,...,0.006142,0.004279,0.005550,0.011236,0.010861,0.005055,0.000000,0.008307,0.009602,0.003405
4,40972,2.172367e+08,0.064524,0.056894,0.055694,0.057410,0.049283,0.048565,0.048002,0.048425,...,0.049171,0.051556,0.055586,0.049027,0.026494,0.052469,0.056334,0.053705,0.049452,0.038607
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23275,ZNF791,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23276,ZNF862,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23277,ZNF91,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23278,ZRANB2,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23279,hsa-miR-3194-3p,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

,gene_name,Closest_TSS,TBI-AUTO73325-PT-3149,PT-BZHL,PT-BZCH,PT-BY9H,TBI-AUTO73307-PT-314I,TBI-AUTO73043-PT-35BD,PT-BZI5,PT-BZ1A,...,TBI-AUTO72955-PT-35OC,TBI-AUTO73291-PT-35OD,PT-BZD7,PT-BZG8,PT-C1N8,PT-BYJP,PT-BZHV,PT-BZI2,TBI-AUTO73257-PT-35OE,PT-BZD3
0,1/2-SBSRNA4,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,40969,1.928757e+08,0.455367,0.445996,0.431180,0.449385,0.443984,0.461588,0.450010,0.451255,...,0.451212,0.474548,0.450920,0.464083,0.455649,0.469531,0.459546,0.445075,0.440247,0.473129
2,40970,1.855144e+08,0.053927,0.049527,0.048195,0.042055,0.051275,0.046544,0.043220,0.038363,...,0.047662,0.045282,0.048769,0.044007,0.044640,0.044352,0.052840,0.057617,0.054666,0.044574
3,40971,1.263664e+08,0.065878,0.071462,0.068046,0.064942,0.068278,0.069006,0.063565,0.058064,...,0.071960,0.068659,0.073089,0.057048,0.047540,0.063163,0.073969,0.060095,0.087613,0.044895
4,40972,2.172367e+08,0.155312,0.137769,0.140559,0.157943,0.141373,0.130886,0.142527,0.136348,...,0.128640,0.144662,0.143587,0.163197,0.133078,0.143944,0.151770,0.139862,0.138751,0.149246
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23275,ZNF791,1.272173e+07,0.051714,0.037007,0.041184,0.046509,0.044618,0.041508,0.038769,0.036825,...,0.040514,0.050522,0.051470,0.045516,0.037322,0.042542,0.038704,0.040140,0.026948,0.037751
23276,ZNF862,1.495355e+08,0.034747,0.021135,0.023729,0.012815,0.031746,0.009904,0.009447,0.014334,...,0.024416,0.025586,0.031914,0.014402,0.002733,0.016691,0.017068,0.033253,0.011848,0.008686
23277,ZNF91,2.357827e+07,0.057134,0.043614,0.053993,0.036108,0.046052,0.039620,0.041359,0.043246,...,0.034475,0.046898,0.046136,0.045172,0.012000,0.046121,0.047162,0.051674,0.027724,0.044179
23278,ZRANB2,7.154697e+07,0.046917,0.042107,0.043511,0.037403,0.040875,0.054482,0.041680,0.030635,...,0.039016,0.039753,0.041944,0.044347,0.030421,0.046929,0.039487,0.047963,0.041057,0.043777
23279,hsa-miR-3194-3p,3.137928e+07,0.557829,0.645971,0.555485,0.625114,0.647693,0.589112,0.564723,0.616729,...,0.615957,0.652565,0.648132,0.632591,0.618641,0.640838,0.619501,0.586397,0.617261,0.617818

## 4.Unify genes and patient samples within datasets

### 4.1 Unify gene and TSS for methylation, copynumer, and gene expression data

In [53]:
gene_expression = gene_expression_new.copy()
gene_expression

,gene_name,525_120515_0,383_120503_0,93_120417_0,610_120523_0,560_120517_0,492_120515_0,576_120521_0,150_120419_0,416_120503_0,...,831_130725_8,901_131010_8,894_130923_8,938_131101_8,942_131101_8,939_131101_8,895_130923_8,829_130725_8,944_131107_8,775_130528_8
0,7SK,233.11,148.79,177.12,197.38,238.15,156.24,340.67,111.16,212.84,...,63.46,70.21,89.59,85.90,140.91,132.21,125.26,67.56,111.18,89.51
1,A1BG,2.93,2.44,3.78,2.82,3.26,3.19,3.40,3.62,2.82,...,1.23,1.86,1.66,1.59,1.32,1.59,1.03,1.95,3.23,1.98
2,A1CF,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
3,A2M,15.37,16.15,31.83,32.41,29.42,33.33,46.22,30.92,42.70,...,26.35,33.72,46.68,34.92,32.48,26.25,62.94,25.71,21.72,34.44
4,A2M-AS1,0.59,0.79,0.71,0.63,0.39,0.77,0.34,0.57,0.45,...,1.18,0.95,0.57,0.76,0.45,1.40,0.75,1.09,1.52,0.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37893,ZYG11B,10.24,7.94,6.20,6.08,5.98,17.90,5.65,10.92,7.60,...,17.64,16.46,14.33,13.96,11.23,14.36,8.10,12.67,14.02,11.08
37894,ZYX,55.86,62.33,77.69,54.95,55.05,49.34,62.83,86.67,69.39,...,42.19,50.30,47.13,36.20,32.47,41.14,33.11,55.77,35.80,44.74
37895,ZZEF1,5.57,6.09,5.19,5.36,5.53,8.74,9.64,9.37,6.14,...,5.91,8.76,6.18,5.91,6.18,5.03,4.97,5.45,6.13,6.53
37896,ZZZ3,4.73,5.13,3.41,4.87,5.21,6.66,5.09,5.12,4.76,...,8.89,6.25,8.17,8.35,8.74,7.51,6.41,6.73,9.76,8.06
37897,hsa-mir-423,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

In [54]:
Upstream_df

,gene_name,Closest_TSS,TBI-AUTO73325-PT-3149,PT-BZHL,PT-BZCH,PT-BY9H,TBI-AUTO73307-PT-314I,TBI-AUTO73043-PT-35BD,PT-BZI5,PT-BZ1A,...,TBI-AUTO72955-PT-35OC,TBI-AUTO73291-PT-35OD,PT-BZD7,PT-BZG8,PT-C1N8,PT-BYJP,PT-BZHV,PT-BZI2,TBI-AUTO73257-PT-35OE,PT-BZD3
0,1/2-SBSRNA4,110354972.0,0.931928,0.922927,0.921658,0.934680,0.950280,0.915567,0.895290,0.942072,...,0.929474,0.932108,0.909341,0.921341,0.930176,0.916491,0.913546,0.936391,0.905927,0.942917
1,40969,220960038.0,0.718230,0.698030,0.712573,0.705048,0.734309,0.771367,0.782897,0.704986,...,0.766211,0.675562,0.720371,0.689035,0.618610,0.764157,0.576607,0.754224,0.745078,0.710471
2,40970,220921675.0,0.868322,0.845299,0.849537,0.892048,0.881078,0.867949,0.886519,0.902767,...,0.874877,0.851768,0.870165,0.878390,0.893037,0.901645,0.876906,0.870745,0.852633,0.877366
3,40971,126366439.0,0.914631,0.890200,0.893712,0.904816,0.934809,0.901929,0.918363,0.889949,...,0.907466,0.905140,0.898941,0.857999,0.960562,0.964220,0.896651,0.901460,0.907702,0.936499
4,40972,217236749.0,0.689192,0.726004,0.691986,0.669473,0.690793,0.725609,0.711018,0.717188,...,0.822901,0.727588,0.706725,0.726323,0.695048,0.800269,0.685743,0.758808,0.726784,0.716149
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23275,ZNF791,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23276,ZNF862,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23277,ZNF91,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23278,ZRANB2,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23279,hsa-miR-3194-3p,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [55]:
ensembl_data_unique_gene = pd.read_csv("./ROSMAP-raw/Meta-Data/mart_export_unique_gene.txt")
ensembl_data_unique_gene

      Gene name
0         MT-TF
1       MT-RNR1
2         MT-TV
3       MT-RNR2
4        MT-TL1
...         ...
48105    ZNF593
48106    CNKSR1
48107    ZPLD2P
48108   DDX11L2
48109    WASH7P

[48110 rows x 1 columns]

In [56]:
#filter the genes not in Ensembl Dataset
gene_expression = gene_expression[gene_expression['gene_name'].isin(ensembl_data_unique_gene['Gene name'])]
Upstream_df = Upstream_df[Upstream_df['gene_name'].isin(ensembl_data_unique_gene['Gene name'])]
protein = protein[protein['gene_name'].isin(ensembl_data_unique_gene['Gene name'])]
cnv_aggregated_del = cnv_aggregated_del[cnv_aggregated_del['gene_name'].isin(ensembl_data_unique_gene['Gene name'])]

In [57]:
# Convert the gene name columns from each DataFrame to sets
gene_expression_genes = set(gene_expression['gene_name'])
print(f"Number of genes in gene_expression: {len(gene_expression_genes)}")
methylation_genes = set(Upstream_df['gene_name'])
print(f"Number of genes in methylation: {len(methylation_genes)}")
protein_genes = set(protein['gene_name'])
print(f"Number of genes in protein: {len(protein_genes)}")
cnv_aggregated_genes = set(cnv_aggregated_del['gene_name'])
print(f"Number of genes in cnv_aggregated: {len(cnv_aggregated_genes)}")

# Find the intersection of these sets
common_genes =  gene_expression_genes | methylation_genes | cnv_aggregated_genes

# Convert the intersection back to a list, if needed
common_genes_list = list(common_genes)

# Print the number of common genes
print(f"Number of common genes: {len(common_genes)}")

Number of genes in gene_expression: 37898
Number of genes in methylation: 17606
Number of genes in protein: 7817
Number of genes in cnv_aggregated: 6419
Number of common genes: 38675

In [58]:
#count the Transcript type
ensembl_data_type = pd.read_csv("./ROSMAP-raw/Meta-Data/mart_export.txt")
ensembl_data_type= ensembl_data_type.rename(columns={'Gene name': 'gene_name'})
ensembl_data_type = ensembl_data_type.drop_duplicates(subset='gene_name', keep='first')
ensembl_data_type
# Now, merge the two dataframes on the 'gene_name' column
gene_expression_transcript = pd.merge(gene_expression, ensembl_data_type, on='gene_name', how='left')
protein_coding_count = (gene_expression_transcript['Transcript type'] == 'protein_coding').sum()
print(f'Number of rows with "protein_coding": {protein_coding_count}')

Upstream_df_transcript = pd.merge(Upstream_df, ensembl_data_type, on='gene_name', how='left')
protein_coding_count = (Upstream_df_transcript['Transcript type'] == 'protein_coding').sum()
print(f'Number of rows with "protein_coding": {protein_coding_count}')

protein_transcript = pd.merge(protein, ensembl_data_type, on='gene_name', how='left')
protein_coding_count = (protein_transcript['Transcript type'] == 'protein_coding').sum()
print(f'Number of rows with "protein_coding": {protein_coding_count}')

cnv_aggregated_del_transcript = pd.merge(cnv_aggregated_del, ensembl_data_type, on='gene_name', how='left')
protein_coding_count = (cnv_aggregated_del_transcript['Transcript type'] == 'protein_coding').sum()
print(f'Number of rows with "protein_coding": {protein_coding_count}')

Number of rows with "protein_coding": 15387
Number of rows with "protein_coding": 12959
Number of rows with "protein_coding": 6246
Number of rows with "protein_coding": 3268

In [59]:
# common_genes_left = common_genes - common_genes_cnv_with_others
# print(f"Number of common genes: {len(common_genes_left)}")

In [60]:
# cnv_aggregated_filtered = pd.DataFrame(columns=cnv_aggregated.columns)

# for gene in common_genes_cnv_with_others:
#     if gene in cnv_aggregated['Gene_Names'].values:
#         gene_row = cnv_aggregated[cnv_aggregated['Gene_Names'] == gene]
#         cnv_aggregated_filtered = pd.concat([cnv_aggregated_filtered, gene_row])

# for gene in common_genes_left:
#     zero_data = [0] * (len(cnv_aggregated.columns) - 1)
#     zero_row = pd.DataFrame([[gene] + zero_data], columns=cnv_aggregated.columns)
#     cnv_aggregated_filtered = pd.concat([cnv_aggregated_filtered, zero_row])

# cnv_aggregated_filtered.reset_index(drop=True, inplace=True)

In [61]:
# cnv_aggregated_filtered

#### 4.1.1 Make the gene expression, mutation, copy number and proteomics data inputted

In [62]:
common_genes_df = pd.DataFrame(common_genes, columns=['gene_name'])
common_genes_df

       gene_name
0         MRPL45
1          MANCR
2          CCER2
3        MIR3138
4      LINC03040
...          ...
38670      ERP27
38671      EPPIN
38672      CDH11
38673     OR52H1
38674  LINC01825

[38675 rows x 1 columns]

In [63]:
merged_data_transcript_Upstream_df = pd.merge(common_genes_df, ensembl_data_type, on='gene_name', how='left')
protein_coding_count = (merged_data_transcript_Upstream_df['Transcript type'] == 'protein_coding').sum()
print(f'Number of rows with "protein_coding": {protein_coding_count}')

Number of rows with "protein_coding": 15611

In [64]:
unique_values = merged_data_transcript_Upstream_df['Transcript type'].value_counts()
unique_values

Transcript type
protein_coding                        15611
processed_pseudogene                   6268
lncRNA                                 5057
snRNA                                  1794
protein_coding_CDS_not_defined         1416
unprocessed_pseudogene                 1412
miRNA                                  1398
nonsense_mediated_decay                1089
misc_RNA                                954
retained_intron                         954
transcribed_unprocessed_pseudogene      617
rRNA_pseudogene                         480
snoRNA                                  434
transcribed_processed_pseudogene        299
IG_V_pseudogene                         165
IG_V_gene                               132
transcribed_unitary_pseudogene          118
TR_V_gene                                91
TR_J_gene                                71
unitary_pseudogene                       67
TR_V_pseudogene                          33
protein_coding_LoF                       31
IG_D_gene                                27
rRNA                                     25
Mt_tRNA                                  22
scaRNA                                   19
IG_J_gene                                18
IG_C_gene                                14
TEC                                       9
processed_transcript                      8
IG_C_pseudogene                           8
TR_C_gene                                 6
non_stop_decay                            5
ribozyme                                  5
vault_RNA                                 4
TR_J_pseudogene                           4
IG_J_pseudogene                           3
TR_D_gene                                 3
Mt_rRNA                                   2
translated_processed_pseudogene           1
scRNA                                     1
Name: count, dtype: int64

In [65]:
gene_expression_inputted = pd.merge(common_genes_df ,gene_expression,on='gene_name',how='outer').fillna(0)
protein_inputted = pd.merge(common_genes_df, protein, on='gene_name', how='outer').fillna(0)

Upstream_df_inputted = pd.merge(common_genes_df, Upstream_df,on='gene_name',how='outer').fillna(0)
Distal_Promoter_df_inputted = pd.merge(common_genes_df, Distal_Promoter_df,on='gene_name',how='outer').fillna(0)
Proximal_Promoter_df_inputted = pd.merge(common_genes_df, Proximal_Promoter_df,on='gene_name',how='outer').fillna(0)
Core_Promoter_df_inputted = pd.merge(common_genes_df, Core_Promoter_df,on='gene_name',how='outer').fillna(0)
Downstream_df_inputted = pd.merge(common_genes_df, Downstream_df,on='gene_name',how='outer').fillna(0)

cnv_aggregated_inputted_del = pd.merge(common_genes_df, cnv_aggregated_del, on='gene_name', how='outer').fillna(-1)
cnv_aggregated_inputted_dup = pd.merge(common_genes_df, cnv_aggregated_dup, on='gene_name', how='outer').fillna(-1)
cnv_aggregated_inputted_mcnv = pd.merge(common_genes_df, cnv_aggregated_mcnv, on='gene_name', how='outer').fillna(-1)

gene_expression_inputted

,gene_name,525_120515_0,383_120503_0,93_120417_0,610_120523_0,560_120517_0,492_120515_0,576_120521_0,150_120419_0,416_120503_0,...,831_130725_8,901_131010_8,894_130923_8,938_131101_8,942_131101_8,939_131101_8,895_130923_8,829_130725_8,944_131107_8,775_130528_8
0,MRPL45,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
1,MANCR,0.00,0.05,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2,CCER2,3.21,2.81,6.68,4.99,5.51,2.15,3.51,3.81,4.54,...,1.34,2.29,2.90,2.27,2.36,2.82,2.65,3.17,1.56,3.40
3,MIR3138,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,LINC03040,0.07,0.39,0.72,0.12,0.14,0.19,0.51,0.47,0.22,...,0.14,0.42,0.31,0.37,0.29,0.13,0.58,0.21,0.25,0.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38670,ERP27,0.02,0.03,0.16,0.02,0.04,0.05,0.04,0.13,0.05,...,0.03,0.03,0.06,0.00,0.07,0.00,0.08,0.00,0.08,0.03
38671,EPPIN,0.01,0.01,0.02,0.02,0.00,0.01,0.00,0.00,0.01,...,0.00,0.00,0.00,0.04,0.00,0.02,0.00,0.06,0.00,0.00
38672,CDH11,3.64,2.91,1.84,3.25,2.97,6.84,6.74,2.62,3.05,...,4.53,3.68,5.59,4.23,4.17,3.04,4.24,3.04,4.59,3.62
38673,OR52H1,0.00,0.00,0.00,0.02,0.00,0.00,0.00,0.02,0.00,...,0.00,0.00,0.00,0.00,0.06,0.00,0.00,0.00,0.00,0.00
38674,LINC01825,0.00,0.00,0.03,0.00,0.03,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00

#### 4.1.2  Intersecting genes with various databases

In [66]:
import pandas as pd
# Add the gene names from databases like [KEGG / BioGRID] to intersect with the common genes
# KEGG
kegg_pathway_df = pd.read_csv('./Regulatory-network-data/KEGG/full_kegg_pathway_list.csv')
kegg_pathway_df = kegg_pathway_df[['source', 'target', 'pathway_name']]
kegg_df = kegg_pathway_df[kegg_pathway_df['pathway_name'].str.contains('signaling pathway|signaling pathways', case=False)]
print(kegg_df['pathway_name'].value_counts())
kegg_df = kegg_df.rename(columns={'source': 'src', 'target': 'dest'})
src_list = list(kegg_df['src'])
dest_list = list(kegg_df['dest'])
path_list = list(kegg_df['pathway_name'])
# ADJUST ALL GENES TO UPPERCASE
up_src_list = []
for src in src_list:
    up_src = src.upper()
    up_src_list.append(up_src)
up_dest_list = []
for dest in dest_list:
    up_dest = dest.upper()
    up_dest_list.append(up_dest)
up_kegg_conn_dict = {'src': up_src_list, 'dest': up_dest_list}
up_kegg_df = pd.DataFrame(up_kegg_conn_dict)
up_kegg_df = up_kegg_df.drop_duplicates()
up_kegg_df.to_csv('./Regulatory-network-data/KEGG/up_kegg.csv', index=False, header=True)
kegg_gene_list = list(set(list(up_kegg_df['src']) + list(up_kegg_df['dest'])))
print('----- NUMBER OF GENES IN KEGG: ' + str(len(kegg_gene_list)) + ' -----')
print(up_kegg_df.shape)

up_kegg_path_conn_dict = {'src': up_src_list, 'dest': up_dest_list, 'path': path_list}
up_kegg_path_df = pd.DataFrame(up_kegg_path_conn_dict)
up_kegg_path_df = up_kegg_path_df.drop_duplicates()
up_kegg_path_df.to_csv('./Regulatory-network-data/KEGG/up_kegg_path.csv', index=False, header=True)
kegg_path_gene_list = list(set(list(up_kegg_path_df['src']) + list(up_kegg_path_df['dest'])))
print('----- NUMBER OF GENES IN KEGG PATH: ' + str(len(kegg_path_gene_list)) + ' -----')
print(up_kegg_path_df.shape)

pathway_name
PI3K-Akt signaling pathway                                  3992
JAK-STAT signaling pathway                                  3280
Chemokine signaling pathway                                 2766
MAPK signaling pathway                                      2002
cAMP signaling pathway                                      1680
Ras signaling pathway                                       1640
Rap1 signaling pathway                                      1304
Calcium signaling pathway                                   1260
Apelin signaling pathway                                    1011
Wnt signaling pathway                                        935
mTOR signaling pathway                                       836
Hippo signaling pathway                                      830
Insulin signaling pathway                                    721
Glucagon signaling pathway                                   707
Relaxin signaling pathway                                    684
Phospholipase D signaling pathway                            676
Thyroid hormone signaling pathway                            650
FoxO signaling pathway                                       632
AGE-RAGE signaling pathway in diabetic complications         627
Oxytocin signaling pathway                                   609
AMPK signaling pathway                                       564
cGMP-PKG signaling pathway                                   560
Neurotrophin signaling pathway                               549
Estrogen signaling pathway                                   515
Signaling pathways regulating pluripotency of stem cells     500
IL-17 signaling pathway                                      500
C-type lectin receptor signaling pathway                     427
HIF-1 signaling pathway                                      407
Sphingolipid signaling pathway                               395
T cell receptor signaling pathway                            376
TGF-beta signaling pathway                                   352
NOD-like receptor signaling pathway                          352
Adipocytokine signaling pathway                              311
PPAR signaling pathway                                       305
ErbB signaling pathway                                       264
Toll-like receptor signaling pathway                         263
GnRH signaling pathway                                       248
NF-kappa B signaling pathway                                 238
Notch signaling pathway                                      238
VEGF signaling pathway                                       236
Hedgehog signaling pathway                                   227
Prolactin signaling pathway                                  219
RIG-I-like receptor signaling pathway                        191
Fc epsilon RI signaling pathway                              182
B cell receptor signaling pathway                            177
TNF signaling pathway                                        167
p53 signaling pathway                                        111
Hippo signaling pathway - multiple species                    96
Name: count, dtype: int64
----- NUMBER OF GENES IN KEGG: 2241 -----
(21041, 2)
----- NUMBER OF GENES IN KEGG PATH: 2241 -----
(30733, 3)

In [67]:
# BioGRID
biogrid_df = pd.read_table('./Regulatory-network-data/BioGrid/BIOGRID-ALL-3.5.174.mitab.Symbol.txt', delimiter = '\t')
eh_list = list(biogrid_df['e_h'])
et_list = list(biogrid_df['e_t'])
# ADJUST ALL GENES TO UPPERCASE
up_eh_list = []
for eh in eh_list:
    up_eh = eh.upper()
    up_eh_list.append(up_eh)
up_et_list = []
for et in et_list:
    up_et = et.upper()
    up_et_list.append(up_et)
up_biogrid_conn_dict = {'src': up_eh_list, 'dest': up_et_list}
up_biogrid_df = pd.DataFrame(up_biogrid_conn_dict)
print(up_biogrid_df)
print(up_biogrid_df.shape)
up_biogrid_df.to_csv('./Regulatory-network-data/BioGrid/up_biogrid.csv', index = False, header = True)
up_biogrid_gene_list = list(set(list(up_biogrid_df['src']) + list(up_biogrid_df['dest'])))
print('----- NUMBER OF GENES IN BioGRID: ' + str(len(up_biogrid_gene_list)) + ' -----')

           src    dest
0       MAP2K4    FLNC
1         MYPN   ACTN2
2        ACVR1    FNTA
3        GATA2     PML
4         RPA2   STAT3
...        ...     ...
472638   USP18  SAMHD1
472639   USP18    SKP2
472640  SAMHD1   USP18
472641  SAMHD1   CCNA2
472642  SAMHD1    CDK1

[472643 rows x 2 columns]
(472643, 2)
----- NUMBER OF GENES IN BioGRID: 19349 -----

In [68]:
# STRING
string_df = pd.read_csv('./Regulatory-network-data/STRING/9606.protein.links.detailed.v11.0_sym.csv', low_memory=False)
src_list = list(string_df['Source'])
tar_list = list(string_df['Target'])
# ADJUST ALL GENES TO UPPERCASE
up_src_list = []
for src in src_list:
    up_src = src.upper()
    up_src_list.append(up_src)
up_tar_list = []
for tar in tar_list:
    up_tar = tar.upper()
    up_tar_list.append(up_tar)
up_string_conn_dict = {'src': up_src_list, 'dest': up_tar_list}
up_string_df = pd.DataFrame(up_string_conn_dict)
print(up_string_df)
up_string_df.to_csv('./Regulatory-network-data/STRING/up_string.csv', index = False, header = True)
up_string_gene_list = list(set(list(up_string_df['src']) + list(up_string_df['dest'])))
print('----- NUMBER OF GENES IN STRING: ' + str(len(up_string_gene_list)) + ' -----')

          src    dest
0        ARF5  SPTBN2
1        ARF5  KIF13B
2        ARF5   AP1B1
3        ARF5  KIF21A
4        ARF5   TMED7
...       ...     ...
841063  OR6Q1   REEP1
841064  OR6Q1   REEP4
841065  OR6Q1    GNB1
841066  OR6Q1    RTP3
841067  OR6Q1   REEP2

[841068 rows x 2 columns]
----- NUMBER OF GENES IN STRING: 17179 -----

In [69]:
# intersect the [common genes] with the genes in the different databases [KEGG / BioGRID / STRING]
selected_database = 'KEGG'
# selected_database = 'BioGRID'
# selected_database = 'STRING'
if selected_database == 'KEGG':
    edge_common_genes = list(set(common_genes) & set(kegg_gene_list))
    print('----- NUMBER OF INTERSECTED GENES IN KEGG: ' + str(len(edge_common_genes)) + ' -----')
elif selected_database == 'BioGRID':
    edge_common_genes = list(set(common_genes) & set(up_biogrid_gene_list))
    print('----- NUMBER OF INTERSECTED GENES IN BioGRID: ' + str(len(edge_common_genes)) + ' -----')
elif selected_database == 'STRING':
    edge_common_genes = list(set(common_genes) & set(up_string_gene_list))
    print('----- NUMBER OF INTERSECTED GENES IN STRING: ' + str(len(edge_common_genes)) + ' -----')

# filter the genes in the different databases [KEGG / BioGRID / STRING] with the [common genes]
if selected_database == 'KEGG':
    filtered_up_kegg_df = up_kegg_df[up_kegg_df['src'].isin(edge_common_genes) & up_kegg_df['dest'].isin(edge_common_genes)]
    filtered_up_kegg_df = filtered_up_kegg_df.drop_duplicates()
    filtered_up_kegg_df = filtered_up_kegg_df.sort_values(by=['src', 'dest']).reset_index(drop=True)
    print('----- NEW KEGG EDGE CONNECTIONS: ' + str(len(filtered_up_kegg_df)) + ' -----')
    filtered_up_kegg_path_df = up_kegg_path_df[up_kegg_path_df['src'].isin(edge_common_genes) & up_kegg_path_df['dest'].isin(edge_common_genes)]
    filtered_up_kegg_path_df = filtered_up_kegg_path_df.drop_duplicates()
    filtered_up_kegg_path_df = filtered_up_kegg_path_df.sort_values(by=['src', 'dest']).reset_index(drop=True)
    print('----- NEW KEGG PATHWAY CONNECTIONS: ' + str(len(filtered_up_kegg_path_df)) + ' -----')
elif selected_database == 'BioGRID':
    filtered_up_biogrid_df = up_biogrid_df[up_biogrid_df['src'].isin(edge_common_genes) & up_biogrid_df['dest'].isin(edge_common_genes)]
    filtered_up_biogrid_df = filtered_up_biogrid_df.drop_duplicates()
    filtered_up_biogrid_df = filtered_up_biogrid_df.sort_values(by=['src', 'dest']).reset_index(drop=True)
    print('----- NEW BioGRID EDGE CONNECTIONS: ' + str(len(filtered_up_biogrid_df)) + ' -----')
elif selected_database == 'STRING':
    filtered_up_string_df = up_string_df[up_string_df['src'].isin(edge_common_genes) & up_string_df['dest'].isin(edge_common_genes)]
    filtered_up_string_df = filtered_up_string_df.drop_duplicates()
    filtered_up_string_df = filtered_up_string_df.sort_values(by=['src', 'dest']).reset_index(drop=True)
    print('----- NEW STRING EDGE CONNECTIONS: ' + str(len(filtered_up_string_df)) + ' -----')

----- NUMBER OF INTERSECTED GENES IN KEGG: 2143 -----
----- NEW KEGG EDGE CONNECTIONS: 19813 -----
----- NEW KEGG PATHWAY CONNECTIONS: 28759 -----

In [70]:
if selected_database == 'KEGG':
    display(filtered_up_kegg_df)
    display(filtered_up_kegg_path_df)
elif selected_database == 'BioGRID':
    display(filtered_up_biogrid_df)
elif selected_database == 'STRING':
    display(filtered_up_string_df)

         src   dest
0       ACTB   MYL6
1       ACTB  MYL6B
2       ACTB   MYL9
3       ACTB   STK3
4      ACTG1   MYL6
...      ...    ...
19808  ZNRF3   FZD5
19809  ZNRF3   FZD6
19810  ZNRF3   FZD7
19811  ZNRF3   FZD8
19812  ZNRF3   FZD9

[19813 rows x 2 columns]

         src   dest                        path
0       ACTB   MYL6  Oxytocin signaling pathway
1       ACTB  MYL6B  Oxytocin signaling pathway
2       ACTB   MYL9  Oxytocin signaling pathway
3       ACTB   STK3     Hippo signaling pathway
4      ACTG1   MYL6  Oxytocin signaling pathway
...      ...    ...                         ...
28754  ZNRF3   FZD5       Wnt signaling pathway
28755  ZNRF3   FZD6       Wnt signaling pathway
28756  ZNRF3   FZD7       Wnt signaling pathway
28757  ZNRF3   FZD8       Wnt signaling pathway
28758  ZNRF3   FZD9       Wnt signaling pathway

[28759 rows x 3 columns]

#### 4.1.3 Filtering the gene names across the gene expression, cnv, proteomics and methylation

In [71]:
# select common genes in gene expression data
gene_expression_filtered = gene_expression_inputted.loc[gene_expression_inputted['gene_name'].isin(edge_common_genes)]
gene_expression_filtered = gene_expression_filtered.sort_values(by=['gene_name']).reset_index(drop=True)
gene_expression_filtered

,gene_name,525_120515_0,383_120503_0,93_120417_0,610_120523_0,560_120517_0,492_120515_0,576_120521_0,150_120419_0,416_120503_0,...,831_130725_8,901_131010_8,894_130923_8,938_131101_8,942_131101_8,939_131101_8,895_130923_8,829_130725_8,944_131107_8,775_130528_8
0,ABL1,8.84,8.55,7.78,10.04,11.92,7.72,11.81,9.18,8.44,...,7.36,6.76,6.97,7.13,9.99,6.59,8.27,6.87,8.75,10.48
1,ABL2,5.48,4.72,3.95,4.09,4.91,4.87,4.78,5.79,5.07,...,6.69,6.70,6.26,7.27,7.20,5.98,5.14,6.71,8.11,6.38
2,ACAA1,47.72,51.73,53.82,55.76,53.33,36.55,48.76,51.45,56.51,...,35.83,40.62,38.63,41.68,36.64,50.03,47.65,43.69,49.13,46.26
3,ACACA,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
4,ACACB,9.99,4.14,5.25,16.37,10.72,6.32,10.99,6.19,8.42,...,8.07,4.93,6.69,7.33,11.94,7.54,11.21,6.79,4.97,5.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2138,ZFYVE16,6.19,7.05,5.68,6.38,5.10,10.13,10.06,9.68,7.07,...,14.34,12.17,16.64,11.56,10.34,10.75,9.41,8.79,17.05,15.82
2139,ZFYVE9,15.82,15.60,10.21,9.83,9.53,23.22,9.06,15.90,14.09,...,22.38,19.88,14.51,18.18,14.28,17.75,10.73,16.04,12.01,12.59
2140,ZMAT3,17.50,13.84,8.48,9.11,11.44,18.72,14.66,14.55,13.01,...,26.78,20.76,21.36,20.10,24.53,20.34,15.88,19.24,16.10,15.79
2141,ZNF274,3.55,3.07,2.36,3.75,2.11,2.81,9.79,4.56,2.88,...,3.97,5.85,3.75,4.09,3.59,4.57,3.67,3.85,3.38,3.91
2142,ZNRF3,4.77,4.34,3.34,5.86,6.28,4.77,16.58,4.59,5.61,...,7.96,4.48,6.10,7.10,8.03,3.82,8.42,5.20,8.03,6.03

In [ ]:
protein_filtered = protein_inputted.loc[protein_inputted['gene_name'].isin(edge_common_genes)]
protein_filtered = protein_filtered.sort_values(by=['gene_name']).reset_index(drop=True)
protein_filtered

In [ ]:
# select common genes in methylation data
Upstream_df_filtered = Upstream_df_inputted.loc[Upstream_df_inputted['gene_name'].isin(edge_common_genes)]
Upstream_df_filtered = Upstream_df_filtered.sort_values(by=['gene_name']).reset_index(drop=True)
Distal_Promoter_df_filtered = Distal_Promoter_df_inputted.loc[Distal_Promoter_df_inputted['gene_name'].isin(edge_common_genes)]
Distal_Promoter_df_filtered = Distal_Promoter_df_filtered.sort_values(by=['gene_name']).reset_index(drop=True)
Proximal_Promoter_df_filtered = Proximal_Promoter_df_inputted.loc[Proximal_Promoter_df_inputted['gene_name'].isin(edge_common_genes)]
Proximal_Promoter_df_filtered = Proximal_Promoter_df_filtered.sort_values(by=['gene_name']).reset_index(drop=True)
Core_Promoter_df_filtered = Core_Promoter_df_inputted.loc[Core_Promoter_df_inputted['gene_name'].isin(edge_common_genes)]
Core_Promoter_df_filtered = Core_Promoter_df_filtered.sort_values(by=['gene_name']).reset_index(drop=True)
Downstream_df_filtered = Downstream_df_inputted.loc[Downstream_df_inputted['gene_name'].isin(edge_common_genes)]
Downstream_df_filtered = Downstream_df_filtered.sort_values(by=['gene_name']).reset_index(drop=True)

Upstream_df_filtered

In [ ]:
# select common genes in cnv data
cnv_aggregated_filtered_del = cnv_aggregated_inputted_del.loc[cnv_aggregated_inputted_del['gene_name'].isin(edge_common_genes)]
cnv_aggregated_filtered_del = cnv_aggregated_filtered_del.sort_values(by=['gene_name']).reset_index(drop=True)
cnv_aggregated_filtered_dup = cnv_aggregated_inputted_dup.loc[cnv_aggregated_inputted_dup['gene_name'].isin(edge_common_genes)]
cnv_aggregated_filtered_dup = cnv_aggregated_filtered_dup.sort_values(by=['gene_name']).reset_index(drop=True)
cnv_aggregated_filtered_mcnv = cnv_aggregated_inputted_mcnv.loc[cnv_aggregated_inputted_mcnv['gene_name'].isin(edge_common_genes)]
cnv_aggregated_filtered_mcnv = cnv_aggregated_filtered_mcnv.sort_values(by=['gene_name']).reset_index(drop=True)

cnv_aggregated_filtered_del

### 4.2 Make all data use a unified patient ID

In [ ]:
ROSMAP_biospecimen = pd.read_csv('./ROSMAP-raw/Meta-Data/ROSMAP_biospecimen_metadata.csv', sep=',')
ROSMAP_biospecimen

In [ ]:
# Split the 'specimenID' and construct the matching ID
ROSMAP_biospecimen['matching_id'] = ROSMAP_biospecimen['specimenID'].apply(lambda x: '.'.join(x.split('.')[2:4]))

# Update the dictionary mapping with the new matching IDs
matching_id_to_individual_protein = dict(zip(ROSMAP_biospecimen['matching_id'], ROSMAP_biospecimen['individualID']))

# Replace the column names in the protein DataFrame if they are in the matching_id_to_individual_protein mapping
protein_filtered.columns = [matching_id_to_individual_protein.get(col, col) for col in protein_filtered.columns]
protein_filtered

In [ ]:
mirna_ids = protein.columns.tolist()[1:]
individual_ids = protein_filtered.columns.tolist()[1:]

protein_map = pd.DataFrame({
    'individualID': individual_ids,
    'mirna_id': mirna_ids
})

protein_map

In [ ]:
matching_id_to_individual = dict(zip(ROSMAP_biospecimen['specimenID'], ROSMAP_biospecimen['individualID']))
Upstream_df_filtered.columns = [matching_id_to_individual.get(col, col) for col in Upstream_df_filtered.columns]
Distal_Promoter_df_filtered.columns = [matching_id_to_individual.get(col, col) for col in Distal_Promoter_df_filtered.columns]
Proximal_Promoter_df_filtered.columns = [matching_id_to_individual.get(col, col) for col in Proximal_Promoter_df_filtered.columns]
Core_Promoter_df_filtered.columns = [matching_id_to_individual.get(col, col) for col in Core_Promoter_df_filtered.columns]
Downstream_df_filtered.columns = [matching_id_to_individual.get(col, col) for col in Downstream_df_filtered.columns]
Upstream_df_filtered

In [ ]:
mwas_id = methylation_value.columns.tolist()[1:]
individual_ids = Upstream_df_filtered.columns.tolist()[2:]

methylation_map = pd.DataFrame({
    'individualID': individual_ids,
    'mwas_id': mwas_id
})

methylation_map

In [ ]:
def process_gene_column_name(col_name):
    parts = col_name.split('_')
    return '_'.join(parts[:2]) if len(parts) > 1 else col_name
gene_expression_filtered.columns = [process_gene_column_name(col) for col in gene_expression_filtered.columns]
matching_id_to_individual_gene = dict(zip(ROSMAP_biospecimen['specimenID'], ROSMAP_biospecimen['individualID']))
gene_expression_filtered.columns = [matching_id_to_individual_gene.get(col, col) for col in gene_expression_filtered.columns]
gene_expression_filtered

In [ ]:
mrna_id = gene_expression.columns.tolist()[1:]
individual_ids = gene_expression_filtered.columns.tolist()[1:]

gene_expression_map = pd.DataFrame({
    'individualID': individual_ids,
    'mrna_id': mrna_id
})

gene_expression_map

In [ ]:
cnv_aggregated_filtered_del.columns = [matching_id_to_individual.get(col, col) for col in cnv_aggregated_filtered_del.columns]
cnv_aggregated_filtered_dup.columns = [matching_id_to_individual.get(col, col) for col in cnv_aggregated_filtered_dup.columns]
cnv_aggregated_filtered_mcnv.columns = [matching_id_to_individual.get(col, col) for col in cnv_aggregated_filtered_mcnv.columns]
cnv_aggregated_filtered_del

In [ ]:
cnvdata_id = cnv_aggregated_del.columns.tolist()[1:]
individual_ids = cnv_aggregated_filtered_del.columns.tolist()[1:]

cnv_aggregated_map = pd.DataFrame({
    'individualID': individual_ids,
    'cnvdata_id': cnvdata_id
})

cnv_aggregated_map

In [ ]:
combined_individualID = pd.concat([
    protein_map['individualID'],
    methylation_map['individualID'],
    gene_expression_map['individualID'],
    # snphead_updated_withoutNA['individualID'],
    cnv_aggregated_map['individualID'],
    survival['individualID']
]).unique()

# Now we create a new DataFrame that contains all unique 'individualID' and their corresponding values
# from the other columns in the original DataFrames.
# We perform an outer merge to ensure all unique 'individualID' are included.
union_map = pd.DataFrame(combined_individualID, columns=['individualID'])

# Merge with each original DataFrame
union_map = union_map.merge(protein_map, on='individualID', how='outer')
union_map = union_map.merge(methylation_map, on='individualID', how='outer')
union_map = union_map.merge(gene_expression_map, on='individualID', how='outer')
union_map = union_map.merge(cnv_aggregated_map, on='individualID', how='outer')
union_map = union_map.merge(survival[['individualID', 'projid', 'Study']], on='individualID', how='outer')

# Display the merged DataFrame
union_map

In [ ]:
union_map_cleaned = union_map.dropna()
union_map_cleaned.reset_index(drop=True, inplace=True)
union_map_cleaned

### 4.3 Unify patient samples within methylation, copynumer,  gene expression, clinical, proteomics, molecular subtype, and sample type, primary disease datasets

In [ ]:
#clinical data
survival

In [ ]:
#proteomics data
protein_filtered

In [ ]:
# Extract column names starting with 'R' from methylation datasets
R_columns_upstream = [col for col in Upstream_df_filtered.columns if col.startswith('R')]
R_columns_distal = [col for col in Distal_Promoter_df_filtered.columns if col.startswith('R')]
R_columns_proximal = [col for col in Proximal_Promoter_df_filtered.columns if col.startswith('R')]
R_columns_core = [col for col in Core_Promoter_df_filtered.columns if col.startswith('R')]
R_columns_downstream = [col for col in Downstream_df_filtered.columns if col.startswith('R')]
R_columns_cnv =[col for col in cnv_aggregated_filtered_del.columns if col.startswith('R')]
# Extract 'R' columns from other datasets
R_columns_gene_expression = [col for col in gene_expression_filtered.columns if col != 'gene_name']
R_columns_survival = [col for col in survival['individualID'] if col.startswith('R')]
#R_columns_protein = [col for col in protein_filtered.columns if col.startswith('R')]
# Find the intersection of R column names across all DataFrames
common_R_columns = set(R_columns_upstream) & set(R_columns_distal) & set(R_columns_proximal) & set(R_columns_core) & set(R_columns_downstream) &set(R_columns_gene_expression) &set(R_columns_survival) & set(R_columns_cnv)
# Convert the intersection back to a list, if needed
common_R_columns_list = list(common_R_columns)

# Print the number and the list of common R columns
print(f"Number of common R columns: {len(common_R_columns)}")

In [ ]:
# print(R_columns_downstream[0])
# print(f"Methylation Dataset has: {len(R_columns_downstream)}")
# R_columns_downstream_withsurvival = set(R_columns_downstream) & set(R_columns_survival)
# print(f"After intersection with survival: {len(R_columns_downstream_withsurvival)}")

# print(f"Copy Number Variations Dataset has: {len(R_columns_cnv)}")
# R_columns_cnv_withsurvival = set(R_columns_cnv) & set(R_columns_survival)
# print(f"After intersection with survival: {len(R_columns_cnv_withsurvival)}")

# print(f"RNASeq Dataset has: {len(R_columns_gene_expression)}")
# R_columns_gene_expression_withsurvival = set(R_columns_gene_expression) & set(R_columns_survival)
# print(f"After intersection with survival {len(R_columns_gene_expression_withsurvival)}")

# print(f"Proteomics Dataset has: {len(R_columns_protein)}")
# R_columns_protein_withsurvival = set(R_columns_protein) & set(R_columns_survival)
# print(f"After intersection with survival: {len(R_columns_protein_withsurvival)}")
# # R_columns_cnv, 
# # R_columns_gene_expression, 
# # R_columns_survival, 
# # R_columns_protein

In [ ]:
# import venn
# labels = venn.get_labels([
#     R_columns_cnv_withsurvival,
#     R_columns_gene_expression_withsurvival,
#     R_columns_protein_withsurvival,
#     R_columns_downstream_withsurvival
# ], fill=['number'])
# fig, ax = venn.venn4(labels, names=['Copy Number Variations Dataset', 'RNASeq Dataset', 'Proteomics Dataset','Methylation Dataset'])
# fig.show()

In [ ]:
# R_columns_cnv_withsurvival
# R_columns_gene_expression_withsurvival
# R_columns_protein_withsurvival
# R_columns_downstream_withsurvival

# intersections = {
#     'CNV∩RNASeq': R_columns_cnv_withsurvival & R_columns_gene_expression_withsurvival,
#     'CNV∩Proteomics': R_columns_cnv_withsurvival & R_columns_protein_withsurvival,
#     'CNV∩Methylation': R_columns_cnv_withsurvival & R_columns_downstream_withsurvival,
#     'RNASeq∩Proteomics': R_columns_gene_expression_withsurvival & R_columns_protein_withsurvival,
#     'RNASeq∩Methylation': R_columns_gene_expression_withsurvival & R_columns_downstream_withsurvival,
#     'Proteomics∩Methylation': R_columns_protein_withsurvival & R_columns_downstream_withsurvival,
#     'CNV∩RNASeq∩Proteomics': R_columns_cnv_withsurvival & R_columns_gene_expression_withsurvival & R_columns_protein_withsurvival,
#     'CNV∩RNASeq∩Methylation': R_columns_cnv_withsurvival & R_columns_gene_expression_withsurvival & R_columns_downstream_withsurvival,
#     'CNV∩Proteomics∩Methylation': R_columns_cnv_withsurvival & R_columns_protein_withsurvival & R_columns_downstream_withsurvival,
#     'RNASeq∩Proteomics∩Methylation': R_columns_gene_expression_withsurvival & R_columns_protein_withsurvival & R_columns_downstream_withsurvival,
# }

# for name, intersection in intersections.items():
#     print(f"{name}: {len(intersection)} elements")

In [ ]:
# from upsetplot import plot
# import pandas as pd
# import matplotlib.pyplot as plt

# # Sample data: replace these with your actual sets
# sets = {
#     'Copy Number Variations Dataset': R_columns_cnv_withsurvival,
#     'RNASeq Dataset': R_columns_gene_expression_withsurvival,
#     'Proteomics Dataset': R_columns_protein_withsurvival,
#     'Methylation Dataset': R_columns_downstream_withsurvival
# }

# # Identify all unique elements across all sets
# all_elements = set.union(*sets.values())

# # Transform the data for UpSetPlot
# data = []
# for element in all_elements:
#     data.append([
#         element in sets['Copy Number Variations Dataset'],
#         element in sets['RNASeq Dataset'],
#         element in sets['Proteomics Dataset'],
#         element in sets['Methylation Dataset']
#     ])

# # Create a DataFrame
# df = pd.DataFrame(data, columns=['Copy Number Variations Dataset', 'RNASeq Dataset', 'Proteomics Dataset', 'Methylation Dataset'])

# # Convert boolean values to integers
# df = df.astype(int)

# # Prepare the DataFrame for UpSetPlot
# df_upset = df.groupby(list(df.columns)).size()

# # Plot using UpSetPlot
# upset_axes = plot(df_upset, orientation="vertical", show_counts=True,element_size=40)
# if 'matrix' in upset_axes:
#     # Set the tick labels for the 'matrix' part with the dataset names
#     upset_axes['matrix'].set_xticklabels(['Copy Number Variations Dataset', 'Methylation Dataset', 'RNASeq Dataset','Proteomics Dataset'], rotation=90)

# plt.tight_layout()  # Adjust layout to prevent overlap
# plt.show()  # Display the plot

# # totals_ax = upset_axes['totals']
# # totals_ax.tick_params(labelleft=False, left=False)
# # totals_ax.tick_params(bottom=False, labelbottom=False)
# # for spine in totals_ax.spines.values():
# #     spine.set_visible(False)
# # plt.show()

In [ ]:
# Define columns to keep along with common R columns
additional_cols_methylation = ['gene_name']

# Filter each methylation DataFrame
Upstream_df_filtered = Upstream_df_filtered[additional_cols_methylation + common_R_columns_list]
Distal_Promoter_df_filtered = Distal_Promoter_df_filtered[additional_cols_methylation + common_R_columns_list]
Proximal_Promoter_df_filtered = Proximal_Promoter_df_filtered[additional_cols_methylation + common_R_columns_list]
Core_Promoter_df_filtered = Core_Promoter_df_filtered[additional_cols_methylation + common_R_columns_list]
Downstream_df_filtered = Downstream_df_filtered[additional_cols_methylation + common_R_columns_list]

In [ ]:
Core_Promoter_df_filtered

In [ ]:
Upstream_df_filtered

In [ ]:
# Define columns to keep along with common R columns
additional_cols_gene_expression = ['gene_name']

# Filter the gene expression DataFrame
gene_expression_filtered = gene_expression_filtered[additional_cols_gene_expression + common_R_columns_list]
gene_expression_filtered

In [ ]:
# # Define columns to keep along with common R columns
additional_cols_protein = ['gene_name']

# # Filter the protein DataFrame
# protein_filtered = protein_filtered[additional_cols_protein + common_R_columns_list]
# protein_filtered

# remove protein expression sample, so make all it's column as 0
protein_filtered = protein_filtered[additional_cols_protein].copy()
for col in common_R_columns_list:
    if col not in protein_filtered.columns:
        protein_filtered[col] = 0
protein_filtered

In [ ]:
# Define columns to keep along with common R columns
additional_cols_protein = ['gene_name']

# Filter the cnv DataFrame
cnv_aggregated_filtered_del = cnv_aggregated_filtered_del[additional_cols_protein + common_R_columns_list]
cnv_aggregated_filtered_del.reset_index(drop=True, inplace=True)

cnv_aggregated_filtered_dup = cnv_aggregated_filtered_dup[additional_cols_protein + common_R_columns_list]
cnv_aggregated_filtered_dup.reset_index(drop=True, inplace=True)

cnv_aggregated_filtered_mcnv = cnv_aggregated_filtered_mcnv[additional_cols_protein + common_R_columns_list]
cnv_aggregated_filtered_mcnv.reset_index(drop=True, inplace=True)

cnv_aggregated_filtered_del

In [ ]:
survival_filtered = survival[survival['individualID'].isin(common_R_columns_list)]
survival_filtered

In [ ]:
survival_nan_column_proportions = survival_filtered.isna().mean()

# Display the results
print(survival_nan_column_proportions)

In [ ]:
# Calculate the proportion of NaN values in each column
survival_nan_column_proportions = survival_filtered.isna().mean()

# Identify columns to be dropped (where proportion of NaN values is greater than 1/3)
columns_to_drop = survival_nan_column_proportions[survival_nan_column_proportions > 1/3].index.tolist()

# Drop these columns from the DataFrame
survival_filtered = survival_filtered.drop(columns=columns_to_drop)

# List of columns that were dropped
print("Columns dropped:", columns_to_drop)

In [ ]:
survival_filtered

In [ ]:
cols = ['individualID'] + [col for col in survival_filtered.columns if col != 'individualID']
survival_filtered = survival_filtered[cols]
survival_filtered.reset_index(drop=True, inplace=True)
survival_filtered

## 5.Gene name/patient samples

In [ ]:
gene_list = gene_expression_filtered['gene_name']
gene_list

In [ ]:
patient_sample_list = pd.DataFrame(common_R_columns,columns=['sample'])
patient_sample_list

## 6.Save processed datasets

### 6.1 Keep the consistency for dataframes on genes and samples

In [ ]:
# [gene_list]
# gene-tran
sorted_gene_list = gene_list.sort_values()
sorted_gene = sorted_gene_list.tolist()
sorted_gene_tran = [gene + '-TRAN' for gene in sorted_gene]
sorted_gene_tran_df = pd.DataFrame(sorted_gene_tran, columns=['Gene'])
display(sorted_gene_tran_df)
# gene-meth
sorted_gene_methy = [gene + '-METH' for gene in sorted_gene]
sorted_gene_methy_df = pd.DataFrame(sorted_gene_methy, columns=['Gene'])
display(sorted_gene_methy_df)
# gene-protein
sorted_gene_protein = [gene + '-PROT' for gene in sorted_gene]
sorted_gene_protein_df = pd.DataFrame(sorted_gene_protein, columns=['Gene'])
display(sorted_gene_protein_df)
# all-gene
sorted_gene_all = sorted_gene_tran + sorted_gene_methy + sorted_gene_protein
sorted_all_gene_df = pd.DataFrame(sorted_gene_all, columns=['Gene'])
display(sorted_all_gene_df)

In [ ]:
# [patient-sample-list]
sorted_patient_sample_list = patient_sample_list.sort_values(by='sample')['sample'].tolist()
print(sorted_patient_sample_list)
sorted_patient_sample_df = patient_sample_list.sort_values(by='sample').reset_index(drop=True)
display(sorted_patient_sample_df)

In [ ]:
Upstream_df_filtered = Upstream_df_filtered[['gene_name'] + sorted_patient_sample_list]
Distal_Promoter_df_filtered = Distal_Promoter_df_filtered[['gene_name'] + sorted_patient_sample_list]
Proximal_Promoter_df_filtered = Proximal_Promoter_df_filtered[['gene_name'] + sorted_patient_sample_list]
Core_Promoter_df_filtered = Core_Promoter_df_filtered[['gene_name'] + sorted_patient_sample_list]
Downstream_df_filtered = Downstream_df_filtered[['gene_name'] + sorted_patient_sample_list]

Upstream_df_filtered

In [ ]:
cnv_aggregated_filtered_del = cnv_aggregated_filtered_del[['gene_name'] + sorted_patient_sample_list].sort_values(by='gene_name').reset_index(drop=True)
cnv_aggregated_filtered_dup = cnv_aggregated_filtered_dup[['gene_name'] + sorted_patient_sample_list].sort_values(by='gene_name').reset_index(drop=True)
cnv_aggregated_filtered_mcnv = cnv_aggregated_filtered_mcnv[['gene_name'] + sorted_patient_sample_list].sort_values(by='gene_name').reset_index(drop=True)

cnv_aggregated_filtered_del

In [ ]:
gene_expression_filtered = gene_expression_filtered[['gene_name'] + sorted_patient_sample_list].sort_values(by='gene_name').reset_index(drop=True)
gene_expression_filtered

In [ ]:
protein_filtered = protein_filtered[['gene_name'] + sorted_patient_sample_list].sort_values(by='gene_name').reset_index(drop=True)
protein_filtered

In [ ]:
survival_filtered = survival_filtered.sort_values(by='individualID').reset_index(drop=True)
survival_filtered

In [ ]:
# Change it to binary
def modify_ceradsc(value):
    if value in [1, 2]:
        return 0
    elif value in [3, 4]:
        return 1
    else:
        return value  # Keeps other values as they are, if there are any

survival_filtered['ceradsc'] = survival_filtered['ceradsc'].apply(modify_ceradsc)
survival_filtered

In [ ]:
count_zeros = (survival_filtered['ceradsc'] == 0).sum()
count_ones = (survival_filtered['ceradsc'] == 1).sum()
if count_zeros > count_ones:
    zeros_indices = survival_filtered[survival_filtered['ceradsc'] == 0].index
    n_drop = count_zeros - count_ones
    drop_indices = np.random.choice(zeros_indices, n_drop, replace=False)
    survival_filtered = survival_filtered.drop(drop_indices)
survival_filtered = survival_filtered.reset_index(drop=True)
survival_filtered

In [ ]:
count_zeros = (survival_filtered['ceradsc'] == 0).sum()
count_ones = (survival_filtered['ceradsc'] == 1).sum()
count_zeros,count_ones

### 6.2 create output folder and save processed datasets

In [ ]:
import os

# outputfile name
output_folder = 'ROSMAP-process'
# create folder if not exist
if not os.path.exists(output_folder):
    os.makedirs(output_folder)

In [ ]:
# DataFrame needed to be saved
dataframes = {
    'gene-tran-list.csv': sorted_gene_tran_df,
    'gene-methy-list.csv': sorted_gene_methy_df,
    'gene-protein-list.csv': sorted_gene_protein_df,
    'gene-all-list.csv': sorted_all_gene_df,
    'gene-kegg-edge-list.csv': filtered_up_kegg_df,
    'gene-kegg-path-edge-list.csv': filtered_up_kegg_path_df,
    # 'gene-biogrid-edge-list.csv': filtered_up_biogrid_df,
    # 'gene-string-edge-list.csv': filtered_up_string_df,
    'patient-sample-list.csv': sorted_patient_sample_df,
    # 'phenotype-lists.csv': phenotype_lists,
    'processed-genotype-methy-Upstream.csv': Upstream_df_filtered,
    'processed-genotype-methy-Distal-Promoter.csv': Distal_Promoter_df_filtered,
    'processed-genotype-methy-Proximal-Promoter.csv': Proximal_Promoter_df_filtered,
    'processed-genotype-methy-Core-Promoter.csv': Core_Promoter_df_filtered,
    'processed-genotype-methy-Downstream.csv': Downstream_df_filtered,
    'processed-genotype-cnv_del.csv': cnv_aggregated_filtered_del,
    'processed-genotype-cnv_dup.csv': cnv_aggregated_filtered_dup,
    'processed-genotype-cnv_mcnv.csv': cnv_aggregated_filtered_mcnv,
    'processed-genotype-gene-expression.csv': gene_expression_filtered,
    'processed-genotype-proteomics.csv': protein_filtered,
    # 'processed-phenotype-immune-subtype-transposed.csv': immune_subtype_filtered,
    'processed-phenotype-survival-transposed.csv': survival_filtered,
    # 'processed-phenotype-dense-transposed.csv': dense_filtered,
    # 'processed-phenotype-cellsub-transposed.csv': cellsub_filtered
    'processed-mapping-idmap.csv': union_map,
    'processed-mapping-idmap-withoutnull.csv': union_map_cleaned
}

# save to output folder
for file_name, df in dataframes.items():
    df.to_csv(os.path.join(output_folder, file_name), index=False)

## 7.Convert the processed data into node dictionary

In [ ]:
# load processed data
import pandas as pd
import os

# read the file names under the folder
# Define the path to the output folder where CSV files are stored
output_folder = 'ROSMAP-process'

# List of file names you saved earlier
file_names = [
    'gene-tran-list', 'gene-methy-list', 'gene-protein-list', 'gene-all-list', 
    'gene-kegg-edge-list', 'gene-kegg-path-edge-list', 
    # 'gene-biogrid-edge-list', 
    # 'gene-string-edge-list',
    'patient-sample-list', 'processed-genotype-methy-Upstream', 
    'processed-genotype-methy-Distal-Promoter', 
    'processed-genotype-methy-Proximal-Promoter', 
    'processed-genotype-methy-Core-Promoter', 'processed-genotype-methy-Downstream', 
    'processed-genotype-cnv_del', 'processed-genotype-cnv_dup', 'processed-genotype-cnv_mcnv', 
    'processed-genotype-gene-expression', 
    'processed-genotype-proteomics',
    'processed-phenotype-survival-transposed'
]

# Dictionary to hold the dataframes
dataframes = {}

# Read each file and assign to a dataframe
for file_name in file_names:
    full_path = os.path.join(output_folder, file_name + '.csv')
    dataframes[file_name] = pd.read_csv(full_path)

In [ ]:
# Assign each dataframe to a variable
sorted_gene_tran_df = dataframes['gene-tran-list']
sorted_gene_methy_df = dataframes['gene-methy-list']
sorted_gene_protein_df = dataframes['gene-protein-list']
sorted_all_gene_df = dataframes['gene-all-list']
filtered_up_kegg_df = dataframes['gene-kegg-edge-list']
filtered_up_kegg_path_df = dataframes['gene-kegg-path-edge-list']
# filtered_up_biogrid_df = dataframes['gene-biogrid-edge-list']
# filtered_up_string_df = dataframes['gene-string-edge-list']
sorted_patient_sample_df = dataframes['patient-sample-list']
# phenotype_lists = dataframes['phenotype-lists']
Upstream_df_filtered = dataframes['processed-genotype-methy-Upstream']
Distal_Promoter_df_filtered = dataframes['processed-genotype-methy-Distal-Promoter']
Proximal_Promoter_df_filtered = dataframes['processed-genotype-methy-Proximal-Promoter']
Core_Promoter_df_filtered = dataframes['processed-genotype-methy-Core-Promoter']
Downstream_df_filtered = dataframes['processed-genotype-methy-Downstream']
copynumber_filtered_del = dataframes['processed-genotype-cnv_del']
copynumber_filtered_dup = dataframes['processed-genotype-cnv_dup']
copynumber_filtered_mcnv = dataframes['processed-genotype-cnv_mcnv']
gene_expression_filtered = dataframes['processed-genotype-gene-expression']
protein_filtered = dataframes['processed-genotype-proteomics']
# immune_subtype_filtered = dataframes['processed-phenotype-immune-subtype-transposed']
survival_filtered = dataframes['processed-phenotype-survival-transposed']
# dense_filtered = dataframes['processed-phenotype-dense-transposed']
# cellsub_filtered = dataframes['processed-phenotype-cellsub-transposed']

In [ ]:
# outputfile name
graph_output_folder = 'ROSMAP-graph-data'
# create folder if not exist
if not os.path.exists(graph_output_folder):
    os.makedirs(graph_output_folder)

### 7.1 Make nodes dictionary

In [ ]:
sorted_all_gene_dict = sorted_all_gene_df['Gene'].to_dict()
sorted_all_gene_name_dict = {value: key for key, value in sorted_all_gene_dict.items()}
num_gene = sorted_gene_tran_df.shape[0]
num_gene_protein = sorted_gene_protein_df.shape[0]
nodetype_list = ['Gene-TRAN'] * num_gene + ['Gene-METH'] * num_gene + ['Gene-PROT'] * num_gene_protein
map_all_gene_df = pd.DataFrame({'Gene_num': sorted_all_gene_dict.keys(), 'Gene_name': sorted_all_gene_dict.values(), 'NodeType': nodetype_list})
display(map_all_gene_df)
map_all_gene_df.to_csv(os.path.join(graph_output_folder, 'map-all-gene.csv'), index=False)

### 7.2 Create the edges connection between promoter methylations and proteins

In [ ]:
# [Gene-METH - Gene]
sorted_gene_methy = sorted_gene_methy_df['Gene'].tolist()
sorted_gene_list = sorted_gene_tran_df['Gene'].tolist()
sorted_gene_protein = sorted_gene_protein_df['Gene'].tolist()
sorted_intersection = [gene_protein.replace('-PROT', '-TRAN') for gene_protein in sorted_gene_protein]
gene_meth_edge_df = pd.DataFrame({'src': sorted_gene_methy, 'dest': sorted_gene_list})
display(gene_meth_edge_df)
# [Gene - Gene-PROT]
gene_protein_edge_df = pd.DataFrame({'src': sorted_intersection, 'dest': sorted_gene_protein})
display(gene_protein_edge_df)

In [ ]:
print(sorted_all_gene_name_dict['ABL1-TRAN'])
print(sorted_all_gene_name_dict['ABL1-METH'])
print(sorted_all_gene_name_dict['ABL1-PROT'])
sorted_all_gene_name_dict

In [ ]:
# replace gene name with gene number
gene_meth_num_edge_df = gene_meth_edge_df.copy()
gene_meth_num_edge_df['src'] = gene_meth_edge_df['src'].map(sorted_all_gene_name_dict)
gene_meth_num_edge_df['dest'] = gene_meth_edge_df['dest'].map(sorted_all_gene_name_dict)
display(gene_meth_num_edge_df)
gene_protein_num_edge_df = gene_protein_edge_df.copy()
gene_protein_num_edge_df['src'] = gene_protein_edge_df['src'].map(sorted_all_gene_name_dict)
gene_protein_num_edge_df['dest'] = gene_protein_edge_df['dest'].map(sorted_all_gene_name_dict)
display(gene_protein_num_edge_df)

### 7.3 Concat all edges

In [ ]:
if selected_database == 'KEGG':
    # filtered_up_num_df = filtered_up_kegg_df.copy()
    filtered_up_num_df = filtered_up_kegg_path_df.copy()
elif selected_database == 'BioGRID':
    filtered_up_num_df = filtered_up_biogrid_df.copy()
elif selected_database == 'STRING':
    filtered_up_num_df = filtered_up_string_df.copy()

# Add 'PROT' to the end of each gene name in the 'src' and 'dest' columns
filtered_up_num_df['src'] = filtered_up_num_df['src'].apply(lambda x: x + '-PROT')
filtered_up_num_df['dest'] = filtered_up_num_df['dest'].apply(lambda x: x + '-PROT')

filtered_up_num_df['src'] = filtered_up_num_df['src'].map(sorted_all_gene_name_dict)
filtered_up_num_df['dest'] = filtered_up_num_df['dest'].map(sorted_all_gene_name_dict)
display(filtered_up_num_df)
all_gene_edge_num_df = pd.concat([filtered_up_num_df, gene_meth_num_edge_df, gene_protein_num_edge_df])
display(all_gene_edge_num_df)

num_gene_edge = filtered_up_num_df.shape[0]
num_gene_meth_edge = gene_meth_num_edge_df.shape[0]
num_gene_protein_edge = gene_protein_num_edge_df.shape[0]
edgetype_list = ['Gene-PROT-Gene-PROT'] * num_gene_edge + ['Gene-TRAN-Gene-METH'] * num_gene_meth_edge + ['Gene-TRAN-Gene-PROT'] * num_gene_protein_edge
all_gene_edge_num_df['EdgeType'] = edgetype_list
all_gene_edge_num_df = all_gene_edge_num_df.sort_values(by=['src', 'dest']).reset_index(drop=True)
all_gene_edge_num_df.fillna('internal link', inplace=True)
display(all_gene_edge_num_df)
all_gene_edge_num_df.to_csv(os.path.join(graph_output_folder, 'all-gene-edge-num.csv'), index=False)

In [ ]:
# gene edge interactions without map
all_gene_edge_df = all_gene_edge_num_df.copy()
all_gene_edge_df = all_gene_edge_df.replace(sorted_all_gene_dict)

num_gene_edge = filtered_up_num_df.shape[0]
num_gene_meth_edge = gene_meth_edge_df.shape[0]
num_gene_protein_edge = gene_protein_edge_df.shape[0]
# all_gene_edge_df = all_gene_edge_df.sort_values(by=['src', 'dest']).reset_index(drop=True)
all_gene_edge_df.to_csv(os.path.join(graph_output_folder, 'all-gene-edge.csv'), index=False)
display(all_gene_edge_df)

## 8.Load data into graph format

### 8.1 Form up the input samples

recommends the use of the ceradsc as the classfication for AD types

* ceradsc
* cogdx

In [ ]:
survival_filtered

In [ ]:
survival_filtered_feature_df = survival_filtered.copy()
survival_filtered_feature_df = survival_filtered_feature_df[['individualID', 'ceradsc']]
display(survival_filtered_feature_df)

nan_counts = survival_filtered_feature_df.isna().sum()  # or df.isnull()
print(survival_filtered_feature_df['ceradsc'].unique())
survival_filtered_feature_df.to_csv(os.path.join(graph_output_folder, 'survival-label.csv'), index=False)

### 8.3 Randomize the input label

In [ ]:
# Randomize the survival label
def input_random(randomized, graph_output_folder):
    #randomized = True
    if randomized == True:
        random_survival_filtered_feature_df = survival_filtered_feature_df.sample(frac = 1).reset_index(drop=True)
        random_survival_filtered_feature_df.to_csv(os.path.join(graph_output_folder, 'random-survival-label.csv'), index=False)
    else:
        random_survival_filtered_feature_df = pd.read_csv(os.path.join(graph_output_folder, 'random-survival-label.csv'))
    display(random_survival_filtered_feature_df)

input_random(randomized=False, graph_output_folder=graph_output_folder)

### 8.3 Split the randomized input into K-fold

In [ ]:
# Split deep learning input into training and test
def split_k_fold(k, graph_output_folder):
    random_survival_filtered_feature_df = pd.read_csv(os.path.join(graph_output_folder, 'random-survival-label.csv'))
    num_points = random_survival_filtered_feature_df.shape[0]
    num_div = int(num_points / k)
    num_div_list = [i * num_div for i in range(0, k)]
    num_div_list.append(num_points)
    # Split [random_survival_filtered_feature_df] into [k] folds
    for place_num in range(k):
        low_idx = num_div_list[place_num]
        high_idx = num_div_list[place_num + 1]
        print('\n--------TRAIN-TEST SPLIT WITH TEST FROM ' + str(low_idx) + ' TO ' + str(high_idx) + '--------')
        split_input_df = random_survival_filtered_feature_df[low_idx : high_idx]
        split_input_df.to_csv(os.path.join(graph_output_folder, 'split-random-survival-label-' + str(place_num + 1) + '.csv'), index=False)
        print(split_input_df.shape)

split_k_fold(k=5, graph_output_folder=graph_output_folder)

### 8.4 Reprocess the edge_index file after loading

In [ ]:
import os
import numpy as np
import pandas as pd

graph_output_folder = 'ROSMAP-graph-data'
gene_edge_num_df = pd.read_csv(os.path.join(graph_output_folder, 'all-gene-edge-num.csv'))
src_gene_list = list(gene_edge_num_df['src'])
dest_gene_list = list(gene_edge_num_df['dest'])
edgetype_list = list(gene_edge_num_df['EdgeType'])
path_list = list(gene_edge_num_df['path'])
gene_edge_num_reverse_df = pd.DataFrame({'src': dest_gene_list, 'dest': src_gene_list, 'path': path_list, 'EdgeType': edgetype_list})
gene_edge_num_reverse_wointernal_df = gene_edge_num_reverse_df[~gene_edge_num_reverse_df['path'].str.contains('internal link')]
display(gene_edge_num_df)
display(gene_edge_num_reverse_wointernal_df)
gene_edge_num_all_df = pd.concat([gene_edge_num_df, gene_edge_num_reverse_wointernal_df]).drop_duplicates().sort_values(by=['src', 'dest']).reset_index(drop=True)
display(gene_edge_num_all_df)

In [ ]:
display(gene_edge_num_all_df)
gene_edge_num_all_df.to_csv(os.path.join(graph_output_folder, 'gene_edge_num_all_df.csv'), index=False)

gene_edge_name_all_df = gene_edge_num_all_df.replace(sorted_all_gene_dict)
display(gene_edge_name_all_df)
gene_edge_name_all_df.to_csv(os.path.join(graph_output_folder, 'gene_edge_name_all_df.csv'), index=False)

In [ ]:
# remove internal link
kegg_path_gene_edge_num_all_df = gene_edge_num_all_df[~gene_edge_num_all_df['path'].str.contains('internal link')]
display(kegg_path_gene_edge_num_all_df)
kegg_path_gene_edge_num_all_df.to_csv(os.path.join(graph_output_folder, 'keggpath-gene-edge-num-all.csv'), index=False)
# keep only internal link
internal_gene_edge_num_all_df = gene_edge_num_all_df[gene_edge_num_all_df['path'].str.contains('internal link')]
display(internal_gene_edge_num_all_df)
internal_gene_edge_num_all_df.to_csv(os.path.join(graph_output_folder, 'internal-gene-edge-num-all.csv'), index=False)

kegg_path_gene_edge_name_all_df = kegg_path_gene_edge_num_all_df.replace(sorted_all_gene_dict)
kegg_path_gene_edge_name_all_df.to_csv(os.path.join(graph_output_folder, 'keggpath-gene-edge-name-all.csv'), index=False)
internal_gene_edge_name_all_df = internal_gene_edge_num_all_df.replace(sorted_all_gene_dict)
internal_gene_edge_name_all_df.to_csv(os.path.join(graph_output_folder, 'internal-gene-edge-name-all.csv'), index=False)